puts "Cargando cuencas y subcuencas... DZC"
cuencas_y_subcuencas = [
  { codigo_cuenca: "010" , nombre_cuenca: "Altiplanicas" , region: "XV - I" },
    { codigo_cuenca: "0100" , nombre_cuenca: "Entre Limite Peru-Bolivia y Rio Lauca" , region: "XV - I" },
    { codigo_cuenca: "0101" , nombre_cuenca: "Lago Chungara" , region: "XV - I" },
    { codigo_cuenca: "0102" , nombre_cuenca: "Rio Lauca" , region: "XV - I" },
    { codigo_cuenca: "0103" , nombre_cuenca: "Salar de Surire" , region: "XV - I" },
    { codigo_cuenca: "0104" , nombre_cuenca: "Entre Estero Sencata y Rio Sacaya" , region: "XV - I" },
    { codigo_cuenca: "0105" , nombre_cuenca: "Salar Del Huasco" , region: "XV - I" },
    { codigo_cuenca: "0106" , nombre_cuenca: "Entre Salares Huasco y Coposa" , region: "XV - I" },
    { codigo_cuenca: "0107" , nombre_cuenca: "Salar de Coposa" , region: "XV - I" },
    { codigo_cuenca: "0108" , nombre_cuenca: "Salar de Michincha" , region: "XV - I" },

  { codigo_cuenca: "011" , nombre_cuenca: "Quebrada de la Concordia" , region: "XV" },
    { codigo_cuenca: "0111" , nombre_cuenca: "Quebrada De La Concordia" , region: "XV" },

  { codigo_cuenca: "012" , nombre_cuenca: "Rio Lluta" , region: "XV" },
    { codigo_cuenca: "0120" , nombre_cuenca: "Rio Lluta Alto" , region: "XV" },
    { codigo_cuenca: "0121" , nombre_cuenca: "Rio Lluta Bajo" , region: "XV" },

  { codigo_cuenca: "013" , nombre_cuenca: "Rio San Jose" , region: "XV" },
    { codigo_cuenca: '0130' , nombre_cuenca: 'Azapa Alto' , region: 'XV'},
    { codigo_cuenca: '0131' , nombre_cuenca: 'Rio San Jose' , region: 'XV'},

  { codigo_cuenca: "014" , nombre_cuenca: "Costeras R. San Jose-Q.Camarones" , region: "XV" },
    { codigo_cuenca: '0140' , nombre_cuenca: 'Costeras entre Rio San Jose y Quebrada Vitor' , region: 'XV'},
    { codigo_cuenca: '0141' , nombre_cuenca: 'Quebrada Vitor' , region: 'XV'},
    { codigo_cuenca: '0142' , nombre_cuenca: 'Costeras Entre Quebradas Vitor y Camarones' , region: 'XV'},

  { codigo_cuenca: "015" , nombre_cuenca: "Q. Rio Camarones" , region: "XV - I" },
    { codigo_cuenca: '0150' , nombre_cuenca: 'Rio Camarones Antes Junta Quebrada de Chiza' , region: 'XV - I'},
    { codigo_cuenca: '0151' , nombre_cuenca: 'Quebrada de Chiza' , region: 'XV - I'},
    { codigo_cuenca: '0152' , nombre_cuenca: 'Rio Camarones Bajo' , region: 'XV - I'},

  { codigo_cuenca: "016" , nombre_cuenca: "Costeras R.Camarones-Pampa del Tamarugal" , region: "I" },
    { codigo_cuenca: '0160' , nombre_cuenca: 'Costeras entre Rio Camarones y Quebrada Camiña' , region: 'I'},
    { codigo_cuenca: '0161' , nombre_cuenca: 'Quebrada de Cami±a' , region: 'I'},

  { codigo_cuenca: "017" , nombre_cuenca: "Pampa del Tamarugal" , region: "I" },
    { codigo_cuenca: '0170' , nombre_cuenca: 'Pampa del Tamarugal' , region: 'I'},
    { codigo_cuenca: '0171' , nombre_cuenca: 'Quebrada de Soga' , region: 'I'},
    { codigo_cuenca: '0172' , nombre_cuenca: 'Quebrada de Aroma' , region: 'I'},
    { codigo_cuenca: '0173' , nombre_cuenca: 'Quebrada de Tarapaca' , region: 'I'},
    { codigo_cuenca: '0174' , nombre_cuenca: 'Quebrada de Quipisca' , region: 'I'},
    { codigo_cuenca: '0175' , nombre_cuenca: 'Quebradas Juan Morales, Sagasca  y El Tambillo' , region: 'I'},
    { codigo_cuenca: '0176' , nombre_cuenca: 'Quebrada de Quisma' , region: 'I'},
    { codigo_cuenca: '0177' , nombre_cuenca: 'Quebrada de Chacarilla' , region: 'I'},
    { codigo_cuenca: '0178' , nombre_cuenca: 'Quebrada de Ramada' , region: 'I'},
    { codigo_cuenca: '0179' , nombre_cuenca: 'Quebradas de Cahuisa y de Chipana' , region: 'I'},

  { codigo_cuenca: "018" , nombre_cuenca: "Costeras Tilviche-Loa" , region: "I" },
    { codigo_cuenca: '0180' , nombre_cuenca: 'Entre Quebrada Tilviche y Pampa Orcoma' , region: 'I'},
    { codigo_cuenca: '0181' , nombre_cuenca: 'Pampas Orcoma y Perdiz' , region: 'I'},
    { codigo_cuenca: '0182' , nombre_cuenca: 'Pampas El Carmen y De La Union' , region: 'I'},
    { codigo_cuenca: '0183' , nombre_cuenca: 'Salar De Soronel y Pampa Blanca' , region: 'I'},
    { codigo_cuenca: '0184' , nombre_cuenca: 'Pampa De Las Zorras y Salar Grande' , region: 'I'},

  { codigo_cuenca: "020" , nombre_cuenca: "Fronterizas Salar Michincha-R.Loa" , region: "II" },
    { codigo_cuenca: '0200' , nombre_cuenca: 'Salar De Ollague' , region: 'II'},
    { codigo_cuenca: '0201' , nombre_cuenca: 'Salar De Carcote' , region: 'II'},
    { codigo_cuenca: '0202' , nombre_cuenca: 'Salar De Ascotan' , region: 'II'},

  { codigo_cuenca: "021" , nombre_cuenca: "Rio Loa" , region: "I - II" },
    { codigo_cuenca: '0210' , nombre_cuenca: 'Rio Loa Alto (bajo junta Rio Salado)' , region: 'I - II'},
    { codigo_cuenca: '0211' , nombre_cuenca: 'Loa Medio (entre R.  Salado y Q. de Barrera)' , region: 'I - II'},
    { codigo_cuenca: '0212' , nombre_cuenca: 'Loa Bajo (entre Quebrada Amarga y Desembocadura)' , region: 'I - II'},

  { codigo_cuenca: "022" , nombre_cuenca: "Costeras R.Loa-Q.Caracoles" , region: "II" },
    { codigo_cuenca: '0220' , nombre_cuenca: 'Costeras entre Rio Loa y Q. Iquine (inclusive)' , region: 'II'},
    { codigo_cuenca: '0221' , nombre_cuenca: 'Costeras entre Q. Iquine y Q.Tocopilla (inclusive)' , region: 'II'},
    { codigo_cuenca: '0222' , nombre_cuenca: 'Costeras entre Q. Tocopilla y Q. Gatico (inclusive)' , region: 'II'},
    { codigo_cuenca: '0223' , nombre_cuenca: 'Costeras entre Q. Gatico y Q. Chacaya (exclusive)' , region: 'II'},
    { codigo_cuenca: '0224' , nombre_cuenca: 'Costeras entre Q. Chacaya y Q. Caracoles' , region: ''},

  { codigo_cuenca: "023" , nombre_cuenca: "Fronterizas Salares Atacama-Socompa" , region: "II" },
    { codigo_cuenca: '0230' , nombre_cuenca: 'Cajon' , region: 'II'},
    { codigo_cuenca: '0231' , nombre_cuenca: 'Salar de Tara' , region: 'II'},
    { codigo_cuenca: '0232' , nombre_cuenca: 'Entre Laguna Gucchalajte y Pampa del Lari' , region: 'II'},
    { codigo_cuenca: '0233' , nombre_cuenca: 'Salar de Incaguasi' , region: 'II'},
    { codigo_cuenca: '0234' , nombre_cuenca: 'Salar de Pular' , region: 'II'},

  { codigo_cuenca: "024" , nombre_cuenca: "Endorreica entre Fronterizas y Salar Atacama" , region: "II" },
    { codigo_cuenca: '0240' , nombre_cuenca: 'Laguna Parico, Laguna Helada y Salar de Pujsa' , region: 'II'},
    { codigo_cuenca: '0241' , nombre_cuenca: 'Salar de Quisquiro' , region: 'II'},
    { codigo_cuenca: '0242' , nombre_cuenca: 'Salar de Aguas Calientes y Alto del Lari' , region: 'II'},
    { codigo_cuenca: '0243' , nombre_cuenca: 'Laguna Lejia' , region: 'II'},
    { codigo_cuenca: '0244' , nombre_cuenca: 'Lagunas Miscanti y Meniques' , region: 'II'},
    { codigo_cuenca: '0245' , nombre_cuenca: 'Laguna Tuyajto Chico y Salar de Laco' , region: 'II'},
    { codigo_cuenca: '0246' , nombre_cuenca: 'Laguna de Tuyajto' , region: 'II'},
    { codigo_cuenca: '0247' , nombre_cuenca: 'Salar de Talar y Purisunchi' , region: 'II'},
    { codigo_cuenca: '0248' , nombre_cuenca: 'Laguna del Cabo' , region: 'II'},

  { codigo_cuenca: "025" , nombre_cuenca: "Salar de Atacama" , region: "II" },
    { codigo_cuenca: '0250' , nombre_cuenca: 'Salar de Atacama' , region: 'II'},
    { codigo_cuenca: '0251' , nombre_cuenca: 'Rio San Pedro' , region: 'II'},
    { codigo_cuenca: '0252' , nombre_cuenca: 'Llano De La Paciencia' , region: 'II'},

  { codigo_cuenca: "026" , nombre_cuenca: "Endorreicas Salar Atacama-Vertiente Pacifico" , region: "II" },
    { codigo_cuenca: '0260' , nombre_cuenca: 'Pampa Elvira' , region: 'II'},
    { codigo_cuenca: '0261' , nombre_cuenca: 'Pampa Jardin' , region: 'II'},
    { codigo_cuenca: '0262' , nombre_cuenca: 'Pampa Mariposa (Norte Cerro Mariposa)' , region: 'II'},
    { codigo_cuenca: '0263' , nombre_cuenca: 'Pampa Mariposa (Sur Cerro Mariposa)' , region: 'II'},
    { codigo_cuenca: '0264' , nombre_cuenca: 'Pampa Colorado' , region: 'II'},
    { codigo_cuenca: '0265' , nombre_cuenca: 'Salar Punta Negra' , region: 'II'},
    { codigo_cuenca: '0266' , nombre_cuenca: 'Pampa de Socompa' , region: 'II'},
    { codigo_cuenca: '0267' , nombre_cuenca: 'Salar de Aguas Calientes y Laguna de La Azufrera' , region: 'II'},
    { codigo_cuenca: '0268' , nombre_cuenca: 'Salar de Pajonales' , region: 'II'},

  { codigo_cuenca: "027" , nombre_cuenca: "Quebrada Caracoles" , region: "II" },
    { codigo_cuenca: '0270' , nombre_cuenca: 'Quebrada Caracoles bajo junta Quebrada El Buitre' , region: 'II'},
    { codigo_cuenca: '0271' , nombre_cuenca: 'Q. Caracoles entre Quebrada El Buitre y  Salar del Carmen' , region: 'II'},
    { codigo_cuenca: '0272' , nombre_cuenca: 'Quebrada San Cristobal' , region: 'II'},
    { codigo_cuenca: '0273' , nombre_cuenca: 'Quebrada Honda' , region: 'II'},
    { codigo_cuenca: '0274' , nombre_cuenca: 'Quebrada Salar del Muerto' , region: 'II'},
    { codigo_cuenca: '0275' , nombre_cuenca: 'Quebrada Chimborazo' , region: 'II'},
    { codigo_cuenca: '0276' , nombre_cuenca: 'Q. Caracoles entre Salares Navidad y del Carmen (inclusive) y desembocadura' , region: 'II'},

  { codigo_cuenca: "028" , nombre_cuenca: "Quebrada la Negra" , region: "II" },
    { codigo_cuenca: '0280' , nombre_cuenca: 'Quebrada Mateo hasta Quebrada Grande' , region: 'II'},
    { codigo_cuenca: '0281' , nombre_cuenca: 'Quebrada Grande' , region: 'II'},
    { codigo_cuenca: '0282' , nombre_cuenca: 'Q. La Negra (de Mateo) entre Q. Grande y desembocadura' , region: 'II'},

  { codigo_cuenca: "029" , nombre_cuenca: "Costeras entre Q. la Negra y Q. Pan de Azucar" , region: "II" },
    { codigo_cuenca: '0290' , nombre_cuenca: 'Qs. entre Q. La Negra y Q. de Remedios' , region: 'II'},
    { codigo_cuenca: '0291' , nombre_cuenca: 'Quebrada de Remedios y Quebrada de Izcuna' , region: 'II'},
    { codigo_cuenca: '0292' , nombre_cuenca: 'Qs. entre Q.  de Izcuna y Q.  de Guanillos (inclusive)' , region: 'II'},
    { codigo_cuenca: '0293' , nombre_cuenca: 'Qs. entre Q. de Guanillos y Q.de Taltal' , region: 'II'},
    { codigo_cuenca: '0294' , nombre_cuenca: 'Quebrada de Taltal' , region: 'II'},
    { codigo_cuenca: '0295' , nombre_cuenca: 'Costeras entre Q. Taltal y Q. de la Cachina' , region: 'II'},
    { codigo_cuenca: '0296' , nombre_cuenca: 'Quebrada de La Cachina' , region: 'II'},

  { codigo_cuenca: "030" , nombre_cuenca: "Endorreicas entre Frontera y Vertiente del Pacifico" , region: "III" },
    { codigo_cuenca: '0300' , nombre_cuenca: 'Cuencas al N. del Salar de Pedernales' , region: 'III'},
    { codigo_cuenca: '0301' , nombre_cuenca: 'Cuencas al NE. cuenca del Salar de Pedernales' , region: 'III'},
    { codigo_cuenca: '0302' , nombre_cuenca: 'Salar de Pedernales' , region: 'III'},
    { codigo_cuenca: '0303' , nombre_cuenca: 'Cuencas al SE. cuenca Salar de Pedernales' , region: 'III'},
    { codigo_cuenca: '0304' , nombre_cuenca: 'Salar de Maricunga' , region: 'III'},
    { codigo_cuenca: '0305' , nombre_cuenca: 'Laguna del Negro Francisco' , region: 'III'},

  { codigo_cuenca: "031" , nombre_cuenca: "Costeras Q.Pan de Azucar-R.Salado" , region: "II - III" },
    { codigo_cuenca: '0310' , nombre_cuenca: 'Quebrada Pan de Azucar' , region: 'II - III'},
    { codigo_cuenca: '0311' , nombre_cuenca: 'Quebradas entre Pan de Azucar y Rio Salado' , region: 'II - III'},

  { codigo_cuenca: "032" , nombre_cuenca: "Rio Salado" , region: "III" },
    { codigo_cuenca: '0320' , nombre_cuenca: 'Rio Salado Alto (hasta Quebrada Del Chanaral)' , region: 'III'},
    { codigo_cuenca: '0321' , nombre_cuenca: 'Quebrada Del Chanaral' , region: 'III'},
    { codigo_cuenca: '0322' , nombre_cuenca: 'Rio Salado Bajo' , region: 'III'},

  { codigo_cuenca: "033" , nombre_cuenca: "Costeras e Islas R.Salado-R.Copiapo" , region: "III" },
    { codigo_cuenca: '0330' , nombre_cuenca: 'Costeras entre Rio Salado y Quebrada Flamenco' , region: 'III'},
    { codigo_cuenca: '0331' , nombre_cuenca: 'Quebrada Flamenco' , region: 'III'},
    { codigo_cuenca: '0332' , nombre_cuenca: 'Costeras entre Q. Flamenco y Q. del Morado' , region: 'III'},
    { codigo_cuenca: '0333' , nombre_cuenca: 'Quebrada del Morado' , region: 'III'},
    { codigo_cuenca: '0334' , nombre_cuenca: 'Costeras entre Quebrada del Morado y Rio Copiapo' , region: 'III'},
    { codigo_cuenca: '0335' , nombre_cuenca: 'Islas San Felix, San Ambrosio, Sala y Gomez' , region: 'III'},

  { codigo_cuenca: "034" , nombre_cuenca: "R.  Copiapo" , region: "III" },
    { codigo_cuenca: '0340' , nombre_cuenca: 'Rio Jorquera' , region: 'III'},
    { codigo_cuenca: '0341' , nombre_cuenca: 'Rio Pulido' , region: 'III'},
    { codigo_cuenca: '0342' , nombre_cuenca: 'Rio Manflas' , region: 'III'},
    { codigo_cuenca: '0343' , nombre_cuenca: 'R.  Copiapo Medio' , region: 'III'},
    { codigo_cuenca: '0344' , nombre_cuenca: 'Quebrada Paipote' , region: 'III'},
    { codigo_cuenca: '0345' , nombre_cuenca: 'R.  Copiapo Bajo' , region: 'III'},

  { codigo_cuenca: "035" , nombre_cuenca: "Costeras entre R.Copiapo y Q.Totoral" , region: "III" },
    { codigo_cuenca: '0350' , nombre_cuenca: 'Costeras entre Rio Copiapo y Quebrada Seca (Inclusive)' , region: 'III'},
    { codigo_cuenca: '0351' , nombre_cuenca: 'Quebradas entre Q. Seca y Q. Totoral' , region: 'III'},

  { codigo_cuenca: "036" , nombre_cuenca: "Q.Totoral y Costeras hasta Q.Carrizal" , region: "III" },
    { codigo_cuenca: '0360' , nombre_cuenca: 'Quebrada Totoral' , region: 'III'},
    { codigo_cuenca: '0361' , nombre_cuenca: 'Costeras entre Quebradas Totoral y Carrizal' , region: 'III'},

  { codigo_cuenca: "037" , nombre_cuenca: "Quebrada Carrizal y Costeras hasta R. Huasco" , region: "III" },
    { codigo_cuenca: '0370' , nombre_cuenca: 'Quebradas Carrizal y Carrizalillo' , region: 'III'},

  { codigo_cuenca: "038" , nombre_cuenca: "Rio Huasco" , region: "III - IV" },
    { codigo_cuenca: '0380' , nombre_cuenca: 'Rio Transito' , region: 'III - IV'},
    { codigo_cuenca: '0381' , nombre_cuenca: 'Rio del Carmen' , region: 'III - IV'},
    { codigo_cuenca: '0382' , nombre_cuenca: 'Rio Huasco' , region: 'III - IV'},

  { codigo_cuenca: "039" , nombre_cuenca: "Costeras e Islas entre R.Huasco y Cuarta Region" , region: "III" },
    { codigo_cuenca: '0390' , nombre_cuenca: 'Quebradas entre Rio Huasco y Quebrada San Juan' , region: 'III'},
    { codigo_cuenca: '0391' , nombre_cuenca: 'Quebrada San Juan' , region: 'III'},
    { codigo_cuenca: '0392' , nombre_cuenca: 'Quebrada Honda' , region: 'III'},
    { codigo_cuenca: '0393' , nombre_cuenca: 'Quebrada Los Pozos' , region: 'III'},
    { codigo_cuenca: '0394' , nombre_cuenca: 'Q. Cha±aral' , region: 'III'},
    { codigo_cuenca: '0395' , nombre_cuenca: 'Isla Cha±aral' , region: 'III'},
    { codigo_cuenca: '0396' , nombre_cuenca: 'Quebrada Carrizalillo' , region: 'III'},

  { codigo_cuenca: "040" , nombre_cuenca: "Costeras e Islas entre Tercera Region y Q. Los Choros" , region: "IV" },
    { codigo_cuenca: '0400' , nombre_cuenca: 'Qs. entre Q. Carrizalillo y R. Los Choros' , region: 'IV'},
    { codigo_cuenca: '0402' , nombre_cuenca: 'Isla Gaviota' , region: 'IV'},
    { codigo_cuenca: '0403' , nombre_cuenca: 'Isla Los Choros' , region: 'IV'},
    { codigo_cuenca: '0401' , nombre_cuenca: 'Isla Damas' , region: 'IV'},

  { codigo_cuenca: "041" , nombre_cuenca: "Rio los Choros" , region: "III - IV" },
    { codigo_cuenca: '0410' , nombre_cuenca: 'Q. Los Choros hasta junta Q. del Pelicano' , region: 'III - IV'},
    { codigo_cuenca: '0411' , nombre_cuenca: 'Q.  del Pelicano' , region: 'III - IV'},
    { codigo_cuenca: '0412' , nombre_cuenca: 'Q. Los Choros entre Q. del Pelicano y desembocadura' , region: 'III - IV'},

  { codigo_cuenca: "042" , nombre_cuenca: "Costeras entrre R. Los Choros y R. Elqui" , region: "IV" },
    { codigo_cuenca: '0420' , nombre_cuenca: 'Costeras entre Rio Los Choros y Rio Elqui' , region: 'IV'},

  { codigo_cuenca: "043" , nombre_cuenca: "Rio Elqui" , region: "IV" },
    { codigo_cuenca: '0430' , nombre_cuenca: 'Rio Turbio' , region: 'IV'},
    { codigo_cuenca: '0431' , nombre_cuenca: 'Rio Claro' , region: 'IV'},
    { codigo_cuenca: '0432' , nombre_cuenca: 'R. Elqui Medio' , region: 'IV'},
    { codigo_cuenca: '0433' , nombre_cuenca: 'R. Elqui Bajo' , region: 'IV'},

  { codigo_cuenca: "044" , nombre_cuenca: "Costeras entre Elqui y Limari" , region: "IV" },
    { codigo_cuenca: '0440' , nombre_cuenca: 'E.  El Culebron - Q. El Romeral (Incl.)' , region: 'IV'},
    { codigo_cuenca: '0441' , nombre_cuenca: 'Q. Camarones (Incl. - R. Limari' , region: 'IV'},

  { codigo_cuenca: "045" , nombre_cuenca: "Rio Limari" , region: "IV" },
    { codigo_cuenca: '0450' , nombre_cuenca: 'Rio Hurtado' , region: 'IV'},
    { codigo_cuenca: '0451' , nombre_cuenca: 'Rio Grande Alto (hasta arriba junta Rio Rapel)' , region: 'IV'},
    { codigo_cuenca: '0452' , nombre_cuenca: 'R. Grande Medio (arriba Junta R. Rapel y R. Guatulame o Muro Emb. Paloma)' , region: 'IV'},
    { codigo_cuenca: '0453' , nombre_cuenca: 'R. Guatulame (Muro Embalse Paloma)' , region: 'IV'},
    { codigo_cuenca: '0454' , nombre_cuenca: 'Rio Grande Bajo (entre Embalse Paloma y Rio Hurtado)' , region: 'IV'},
    { codigo_cuenca: '0455' , nombre_cuenca: 'Rio Limari' , region: 'IV'},

  { codigo_cuenca: "046" , nombre_cuenca: "Costeras entre R.Limari y R.Choapa" , region: "IV" },
    { codigo_cuenca: '0460' , nombre_cuenca: 'Costeras entre Rio Limari y Estero El Teniente' , region: 'IV'},
    { codigo_cuenca: '0461' , nombre_cuenca: 'E.  El Teniente y E. El Almendro (Incl.)' , region: 'IV'},
    { codigo_cuenca: '0462' , nombre_cuenca: 'Costeras entre E.  El Almendro y Q. Totoral (Incl.)' , region: 'IV'},
    { codigo_cuenca: '0463' , nombre_cuenca: 'Costeras entre Quebrada Totoral y Rio Choapa' , region: 'IV'},

  { codigo_cuenca: "047" , nombre_cuenca: "Rio Choapa" , region: "IV" },
    { codigo_cuenca: '0470' , nombre_cuenca: 'Rio Choapa Alto (hasta abajo junta Rio Cuncumen)' , region: 'IV'},
    { codigo_cuenca: '0471' , nombre_cuenca: 'Rio Choapa Medio (entre Rios Cuncumen e Illapel)' , region: 'IV'},
    { codigo_cuenca: '0472' , nombre_cuenca: 'Rio Illapel' , region: 'IV'},
    { codigo_cuenca: '0473' , nombre_cuenca: 'Rio Choapa Bajo (entre Rio Illapel y Desembocadura)' , region: 'IV'},

  { codigo_cuenca: "048" , nombre_cuenca: "Costeras entre R.Choapa y R.Quilimari" , region: "IV" },
    { codigo_cuenca: '0480' , nombre_cuenca: 'Costeras entre Estero Millahue y Estero Pupio' , region: 'IV'},
    { codigo_cuenca: '0481' , nombre_cuenca: 'Estero Pupio' , region: 'IV'},
    { codigo_cuenca: '0482' , nombre_cuenca: 'Costeras entre Estero Pupio y Rio Quilimari' , region: 'IV'},

  { codigo_cuenca: "049" , nombre_cuenca: "Rio QuiLimari" , region: "IV" },
    { codigo_cuenca: '0490' , nombre_cuenca: 'Rio Quilimari hasta Muro Embalse Culimo' , region: 'IV'},

  { codigo_cuenca: "050" , nombre_cuenca: "Costeras Quilimari-Petorca" , region: "V" },
    { codigo_cuenca: '0500' , nombre_cuenca: 'Costera Quilimari - Petorca' , region: 'V'},

  { codigo_cuenca: "051" , nombre_cuenca: "Rio Petorca" , region: "V" },
    { codigo_cuenca: '0510' , nombre_cuenca: 'Rio Petorca Alto (hasta despues Junta Rio Sobrante)' , region: 'V'},
    { codigo_cuenca: '0511' , nombre_cuenca: 'Petorca Medio' , region: 'V'},
    { codigo_cuenca: '0512' , nombre_cuenca: 'Rio Petorca Bajo (Entre Las Palmas y Desembocadura)' , region: 'V'},

  { codigo_cuenca: "052" , nombre_cuenca: "Rio Ligua" , region: "V" },
    { codigo_cuenca: '0520' , nombre_cuenca: 'Rio Ligua Alto (Estero Alicahue)' , region: 'V'},
    { codigo_cuenca: '0521' , nombre_cuenca: 'Rio Ligua Medio (entre Quebrada La Cerrada y Los Angeles)' , region: 'V'},
    { codigo_cuenca: '0522' , nombre_cuenca: 'Rio Ligua Bajo (Entre Estero Los Angeles y Desembocadura)' , region: 'V'},

  { codigo_cuenca: "053" , nombre_cuenca: "Costeras Ligua-Aconcagua" , region: "V" },
    { codigo_cuenca: '0530' , nombre_cuenca: 'Costeras entre Estero Ligua y Estero Catapilco' , region: 'V'},
    { codigo_cuenca: '0531' , nombre_cuenca: 'Estero Catapilco' , region: 'V'},
    { codigo_cuenca: '0532' , nombre_cuenca: 'Costeras entre Estero Catapilco y Rio Aconcagua' , region: 'V'},

  { codigo_cuenca: "054" , nombre_cuenca: "Rio Aconcagua" , region: "V" },
    { codigo_cuenca: '0540' , nombre_cuenca: 'Aconcagua Alto' , region: 'V'},
    { codigo_cuenca: '0541' , nombre_cuenca: 'Aconcagua Medio' , region: 'V'},
    { codigo_cuenca: '0542' , nombre_cuenca: 'Aconcagua Bajo' , region: 'V'},

  { codigo_cuenca: "055" , nombre_cuenca: "Costeras entre Aconcagua y Maipo" , region: "V" },
    { codigo_cuenca: '0550' , nombre_cuenca: 'E. Marga-Marga' , region: 'V'},
    { codigo_cuenca: '0551' , nombre_cuenca: 'Lago Pe±uelas' , region: 'V'},
    { codigo_cuenca: '0552' , nombre_cuenca: 'E. Casablanca y E.  San Jeronimo (Incl.)' , region: 'V'},
    { codigo_cuenca: '0553' , nombre_cuenca: 'E. del Rosario (Incl.) a R. Maipo' , region: 'V'},

  { codigo_cuenca: "056" , nombre_cuenca: "Islas del Pacifico" , region: "V" },
    { codigo_cuenca: '0560' , nombre_cuenca: 'Islas de Juan Fernandez' , region: 'V'},
    { codigo_cuenca: '0561' , nombre_cuenca: 'Isla de Pascua' , region: 'V'},

  { codigo_cuenca: "057" , nombre_cuenca: "Rio Maipo" , region: "V - XIII - VI" },
    { codigo_cuenca: '0570' , nombre_cuenca: 'Rio Maipo Alto' , region: 'V - XIII - VI'},
    { codigo_cuenca: '0571' , nombre_cuenca: 'Rio Maipo Medio' , region: 'V - XIII - VI'},
    { codigo_cuenca: '0572' , nombre_cuenca: 'R.  Mapocho Alto' , region: 'V - XIII - VI'},
    { codigo_cuenca: '0573' , nombre_cuenca: 'Mapocho Bajo' , region: 'V - XIII - VI'},
    { codigo_cuenca: '0574' , nombre_cuenca: 'Rio Maipo Bajo (Entre Rio Mapocho y Desembocadura)' , region: 'V - XIII - VI'},

  { codigo_cuenca: "058" , nombre_cuenca: "Costeras entre  Maipo y Rapel" , region: "V - XIII" },
    { codigo_cuenca: '0580' , nombre_cuenca: 'Estero Yali' , region: 'V - XIII'},

  { codigo_cuenca: "060" , nombre_cuenca: "Rio Rapel" , region: "V - XIII - VI - VII" },
    { codigo_cuenca: '0600' , nombre_cuenca: 'Rio Cachapoal Alto (Hasta bajo junta Rio Claro)' , region: 'V - XIII - VI - VII'},
    { codigo_cuenca: '0601' , nombre_cuenca: 'Cachapoal Bajo' , region: 'V - XIII - VI - VII'},
    { codigo_cuenca: '0602' , nombre_cuenca: 'Rio Tinguiririca Alto (Hasta bajo junta Rio Claro)' , region: 'V - XIII - VI - VII'},
    { codigo_cuenca: '0603' , nombre_cuenca: 'Tinguiririca Bajo' , region: 'V - XIII - VI - VII'},
    { codigo_cuenca: '0604' , nombre_cuenca: 'Estero Alhue' , region: 'V - XIII - VI - VII'},
    { codigo_cuenca: '0605' , nombre_cuenca: 'Rio Rapel' , region: 'V - XIII - VI - VII'},

  { codigo_cuenca: "061" , nombre_cuenca: "Costeras Rapel-E.Nilahue" , region: "VI - VII" },
    { codigo_cuenca: '0610' , nombre_cuenca: 'Costeras entre Rio Rapel Y Estero Topocalma' , region: 'VI - VII'},
    { codigo_cuenca: '0611' , nombre_cuenca: 'Estero Topocalma' , region: 'VI - VII'},
    { codigo_cuenca: '0612' , nombre_cuenca: 'Costeras entre E. Topocalma y E. Nilahue' , region: 'VI - VII'},
    { codigo_cuenca: '0613' , nombre_cuenca: 'Estero Nilahue' , region: 'VI - VII'},
    { codigo_cuenca: '0614' , nombre_cuenca: 'Costeras entre Estero Nilahue y Limite Region' , region: 'VI - VII'},

  { codigo_cuenca: "070" , nombre_cuenca: "Costeras entre limite Region y R.  Mataquito" , region: "VII" },
    { codigo_cuenca: '0700' , nombre_cuenca: 'Lago Vichuquen' , region: 'VII'},

  { codigo_cuenca: "071" , nombre_cuenca: "Rio Mataquito" , region: "VII" },
    { codigo_cuenca: '0710' , nombre_cuenca: 'Rio Teno' , region: 'VII'},
    { codigo_cuenca: '0711' , nombre_cuenca: 'Rio Lontue' , region: 'VII'},
    { codigo_cuenca: '0712' , nombre_cuenca: 'Rio Mataquito' , region: 'VII'},

  { codigo_cuenca: "072" , nombre_cuenca: "Costeras Mataquito-Maule" , region: "VII" },
    { codigo_cuenca: '0720' , nombre_cuenca: 'Rio Huenchullami' , region: 'VII'},
    { codigo_cuenca: '0721' , nombre_cuenca: 'Costeras entre Rio Huenchullami y Rio maule' , region: 'VII'},

  { codigo_cuenca: "073" , nombre_cuenca: "Rio Maule" , region: "VII - VIII" },
    { codigo_cuenca: '0730' , nombre_cuenca: 'Rio Maule Alto (Hasta antes junta Rio Melado)' , region: 'VII - VIII'},
    { codigo_cuenca: '0731' , nombre_cuenca: 'Rio Melado' , region: 'VII - VIII'},
    { codigo_cuenca: '0732' , nombre_cuenca: 'Maule Medio' , region: 'VII - VIII'},
    { codigo_cuenca: '0733' , nombre_cuenca: 'Perquilauquen Alto' , region: 'VII - VIII'},
    { codigo_cuenca: '0734' , nombre_cuenca: 'Perquilauquen Bajo' , region: 'VII - VIII'},
    { codigo_cuenca: '0735' , nombre_cuenca: 'Rio Loncomilla' , region: 'VII - VIII'},
    { codigo_cuenca: '0736' , nombre_cuenca: 'Rio Maule entre Rio Loncomilla y Rio Claro' , region: 'VII - VIII'},
    { codigo_cuenca: '0737' , nombre_cuenca: 'Rio Claro' , region: 'VII - VIII'},
    { codigo_cuenca: '0738' , nombre_cuenca: 'Maule Bajo' , region: 'VII - VIII'},

  { codigo_cuenca: "074" , nombre_cuenca: "Costeras Maule y Limite Region" , region: "VII - VIII" },
    { codigo_cuenca: '0740' , nombre_cuenca: 'Costeras entre Quebrada Honda y Rio Reloca' , region: 'VII - VIII'},
    { codigo_cuenca: '0741' , nombre_cuenca: 'Rio Reloca' , region: 'VII - VIII'},
    { codigo_cuenca: '0742' , nombre_cuenca: 'Costeras entre Rio Reloca y Rio Curanilahue' , region: 'VII - VIII'},
    { codigo_cuenca: '0743' , nombre_cuenca: 'Rio Curanilahue' , region: 'VII - VIII'},
    { codigo_cuenca: '0744' , nombre_cuenca: 'Costeras entre R. Curanilahue y limite Region (E. Pullay)' , region: 'VII - VIII'},

  { codigo_cuenca: "080" , nombre_cuenca: "Costeras entre limite Region y R. Itata" , region: "VIII" },
    { codigo_cuenca: '0800' , nombre_cuenca: 'Costeras entre Limite Region y R. Taucu (Incl.)' , region: 'VIII'},
    { codigo_cuenca: '0801' , nombre_cuenca: 'Costeras entre Rio Taucu y Rio Itata' , region: 'VIII'},

  { codigo_cuenca: "081" , nombre_cuenca: "Rio Itata" , region: "VII - VIII" },
    { codigo_cuenca: '0810' , nombre_cuenca: 'Ðuble Alto' , region: 'VII - VIII'},
    { codigo_cuenca: '0811' , nombre_cuenca: 'Ðuble Bajo' , region: 'VII - VIII'},
    { codigo_cuenca: '0812' , nombre_cuenca: 'Rio Itata Alto (Hasta Rio Diguillin)' , region: 'VII - VIII'},
    { codigo_cuenca: '0813' , nombre_cuenca: 'Itata Medio' , region: 'VII - VIII'},
    { codigo_cuenca: '0814' , nombre_cuenca: 'Itata Bajo' , region: 'VII - VIII'},

  { codigo_cuenca: "082" , nombre_cuenca: "Costeras e Islas entre Rio Itata y Rio Bio-Bio" , region: "VIII" },
    { codigo_cuenca: '0820' , nombre_cuenca: 'Costeras entre R. Itata y R.  Pingueral (Incl.)' , region: 'VIII'},
    { codigo_cuenca: '0821' , nombre_cuenca: 'Costeras entre Rio Pingueral Y Rio Andalien' , region: 'VIII'},
    { codigo_cuenca: '0822' , nombre_cuenca: 'Rio Andalien' , region: 'VIII'},
    { codigo_cuenca: '0823' , nombre_cuenca: 'Costeras entre Rio Andalien Y Rio Bio-Bio' , region: 'VIII'},
    { codigo_cuenca: '0824' , nombre_cuenca: 'Isla Quiriquina' , region: 'VIII'},

  { codigo_cuenca: "083" , nombre_cuenca: "Rio Bio-Bio" , region: "VIII - IX" },
    { codigo_cuenca: '0830' , nombre_cuenca: 'Rio Bio-Bio Alto (Hasta despues junta Rio Lamin)' , region: 'VIII - IX'},
    { codigo_cuenca: '0831' , nombre_cuenca: 'Rio Bio-Bio entre Rio Ranquil y Rio Duqueco' , region: 'VIII - IX'},
    { codigo_cuenca: '0832' , nombre_cuenca: 'Rio Duqueco' , region: 'VIII - IX'},
    { codigo_cuenca: '0833' , nombre_cuenca: 'Rio Bio-Bio entre Rio Duqueco y Rio Vergara' , region: 'VIII - IX'},
    { codigo_cuenca: '0834' , nombre_cuenca: 'Rio Renaico' , region: 'VIII - IX'},
    { codigo_cuenca: '0835' , nombre_cuenca: 'Rios Malleco y Vergara' , region: 'VIII - IX'},
    { codigo_cuenca: '0836' , nombre_cuenca: 'Rio Bio-Bio entre Rio Vergara y Rio Laja' , region: 'VIII - IX'},
    { codigo_cuenca: '0837' , nombre_cuenca: 'Rio Laja Alto (hasta bajo junta Rio Rucue)' , region: 'VIII - IX'},
    { codigo_cuenca: '0838' , nombre_cuenca: 'Laja Bajo' , region: 'VIII - IX'},
    { codigo_cuenca: '0839' , nombre_cuenca: 'Rio Bio-Bio Bajo' , region: 'VIII - IX'},

  { codigo_cuenca: "084" , nombre_cuenca: "Costeras e Islas entre Rios Bio-Bio y Carampangue" , region: "VIII" },
    { codigo_cuenca: '0840' , nombre_cuenca: 'Isla Santa Maria' , region: 'VIII'},
    { codigo_cuenca: '0841' , nombre_cuenca: 'Costeras entre Rio Bio-Bio y Rio Manco' , region: 'VIII'},
    { codigo_cuenca: '0842' , nombre_cuenca: 'Costeras entre R. Manco (incl.) y R. Laraquete' , region: 'VIII'},
    { codigo_cuenca: '0843' , nombre_cuenca: 'Costeras entre R. Laraquete (incl.) y R. Carampangue' , region: 'VIII'},

  { codigo_cuenca: "085" , nombre_cuenca: "Rio Carampangue" , region: "VIII" },
    { codigo_cuenca: '0850' , nombre_cuenca: 'Rio Carampangue hasta bajo junta Estero Animas' , region: 'VIII'},
    { codigo_cuenca: '0851' , nombre_cuenca: 'Rio Carampangue entre Estero Animas y Rio Colorado' , region: 'VIII'},
    { codigo_cuenca: '0852' , nombre_cuenca: 'Rio Lia' , region: 'VIII'},
    { codigo_cuenca: '0853' , nombre_cuenca: 'R. Carampangue entre arriba R. Colorado y desembocadura' , region: 'VIII'},

  { codigo_cuenca: "086" , nombre_cuenca: "Costeras Carampangue-Lebu" , region: "VIII" },
    { codigo_cuenca: '0860' , nombre_cuenca: 'Costeras entre Rio Carampangue y Punta Lavapie' , region: 'VIII'},
    { codigo_cuenca: '0861' , nombre_cuenca: 'Costeras entre Punta Lavapie y Rio Quiapo' , region: 'VIII'},
    { codigo_cuenca: '0862' , nombre_cuenca: 'Rio Quiapo' , region: 'VIII'},
    { codigo_cuenca: '0863' , nombre_cuenca: 'Costeras entre Rio Quiapo y Rio Lebu' , region: 'VIII'},

  { codigo_cuenca: "087" , nombre_cuenca: "Rio Lebu" , region: "VIII" },
    { codigo_cuenca: '0870' , nombre_cuenca: 'Rio Curanilahue' , region: 'VIII'},
    { codigo_cuenca: '0871' , nombre_cuenca: 'Rio Pilpilco' , region: 'VIII'},
    { codigo_cuenca: '0872' , nombre_cuenca: 'R. Lebu entre junta rios Curanilahue y Pilpilco y desembocadura' , region: 'VIII'},

  { codigo_cuenca: "088" , nombre_cuenca: "Costeras Lebu-Paicavi" , region: "VIII" },
    { codigo_cuenca: '0880' , nombre_cuenca: 'Costeras entre Rio Lebu y Estero Pangue' , region: 'VIII'},
    { codigo_cuenca: '0881' , nombre_cuenca: 'Costeras entre R. Pangue (incl.) y R. Paicavi' , region: 'VIII'},
    { codigo_cuenca: '0882' , nombre_cuenca: 'Rio Paicavi' , region: 'VIII'},

  { codigo_cuenca: "089" , nombre_cuenca: "Costeras e Islas entre R.Paicavi y Limite Region" , region: "VIII - IX" },
    { codigo_cuenca: '0890' , nombre_cuenca: 'Costeras entre R. Paicavi y R. Lleullen' , region: 'VIII - IX'},
    { codigo_cuenca: '0891' , nombre_cuenca: 'R. Lleullen' , region: 'VIII - IX'},
    { codigo_cuenca: '0892' , nombre_cuenca: 'Costeras entre R. Lleullen y R. Tirua' , region: 'VIII - IX'},
    { codigo_cuenca: '0893' , nombre_cuenca: 'Rio Tirua' , region: 'VIII - IX'},
    { codigo_cuenca: '0894' , nombre_cuenca: 'Isla Mocha' , region: 'VIII - IX'},

  { codigo_cuenca: "090" , nombre_cuenca: "Costeras Limite Region y R.  Imperial" , region: "VIII - IX" },
    { codigo_cuenca: '0900' , nombre_cuenca: 'Costeras entre Limite Region Y Rio Imperial' , region: 'VIII - IX'},

  { codigo_cuenca: "091" , nombre_cuenca: "Rio Imperial" , region: "IX" },
    { codigo_cuenca: '0910' , nombre_cuenca: 'Rio Lumaco' , region: 'IX'},
    { codigo_cuenca: '0911' , nombre_cuenca: 'R.  Chol Chol' , region: 'IX'},
    { codigo_cuenca: '0912' , nombre_cuenca: 'Cautin Alto (hasta antes junta R. Quepe)' , region: 'IX'},
    { codigo_cuenca: '0913' , nombre_cuenca: 'Rio Quepe' , region: 'IX'},
    { codigo_cuenca: '0914' , nombre_cuenca: 'Rio Cautin entre Rio Quepe y Rio Chol-Chol' , region: 'IX'},
    { codigo_cuenca: '0915' , nombre_cuenca: 'Rio Imperial' , region: 'IX'},

  { codigo_cuenca: "092" , nombre_cuenca: "Rio Budi" , region: "IX" },
    { codigo_cuenca: '0920' , nombre_cuenca: 'Rio Budi' , region: 'IX'},

  { codigo_cuenca: "093" , nombre_cuenca: "Costeras Entre Rio Budi y Rio Tolten" , region: "IX" },
    { codigo_cuenca: '0930' , nombre_cuenca: 'Costeras entre Rio Budi y Rio Tolten' , region: 'IX'},

  { codigo_cuenca: "094" , nombre_cuenca: "Rio Tolten" , region: "IX" },
    { codigo_cuenca: '0940' , nombre_cuenca: 'Rio Allipen' , region: 'IX'},
    { codigo_cuenca: '0941' , nombre_cuenca: 'Rio Pucon' , region: 'IX'},
    { codigo_cuenca: '0942' , nombre_cuenca: 'Lago Villarica y Tolten Alto' , region: 'IX'},
    { codigo_cuenca: '0943' , nombre_cuenca: 'Tolten Bajo' , region: 'IX'},

  { codigo_cuenca: "095" , nombre_cuenca: "Rio Queule" , region: "IX" },
    { codigo_cuenca: '0950' , nombre_cuenca: 'Rio Queule' , region: 'IX'},

  { codigo_cuenca: "100" , nombre_cuenca: "Costeras entre limite Region y R.Valdivia" , region: "XIV" },
    { codigo_cuenca: '1000' , nombre_cuenca: 'Rio Lingue' , region: 'XIV'},
    { codigo_cuenca: '1001' , nombre_cuenca: 'Costeras entre R.  Lingue y R. Valdivia' , region: 'XIV'},

  { codigo_cuenca: "101" , nombre_cuenca: "Rio Valdivia" , region: "IX - XIV" },
    { codigo_cuenca: '1010' , nombre_cuenca: 'Rio Valdivia Alto (hasta desague Lago Panguipulli)' , region: 'IX - XIV'},
    { codigo_cuenca: '1011' , nombre_cuenca: 'R. San Pedro (Entre desague L. Panguipulli y Bajo R. Quinchilca)' , region: 'IX - XIV'},
    { codigo_cuenca: '1012' , nombre_cuenca: 'Rio Calle Calle' , region: 'IX - XIV'},
    { codigo_cuenca: '1013' , nombre_cuenca: 'Rio Cruces' , region: 'IX - XIV'},
    { codigo_cuenca: '1014' , nombre_cuenca: 'R. Valdivia Bajo' , region: 'IX - XIV'},

  { codigo_cuenca: "102" , nombre_cuenca: "Costeras entre R.Valdivia y R.Bueno" , region: "XIV" },
    { codigo_cuenca: '1020' , nombre_cuenca: 'Costeras entre R. Valdivia y Rio Chaihuin' , region: 'XIV'},
    { codigo_cuenca: '1021' , nombre_cuenca: 'Rio Chaihuin' , region: 'XIV'},
    { codigo_cuenca: '1022' , nombre_cuenca: 'Rio Colun' , region: 'XIV'},
    { codigo_cuenca: '1023' , nombre_cuenca: 'Costeras entre Rio Colun y Rio Bueno' , region: 'XIV'},

  { codigo_cuenca: "103" , nombre_cuenca: "Rio Bueno" , region: "X - XIV" },
    { codigo_cuenca: '1030' , nombre_cuenca: 'Afluentes Lago Ranco' , region: 'X - XIV'},
    { codigo_cuenca: '1031' , nombre_cuenca: 'Rio Bueno entre Lago Ranco y Rio Pilmaiquen' , region: 'X - XIV'},
    { codigo_cuenca: '1032' , nombre_cuenca: 'Rio Pilmaiquen' , region: 'X - XIV'},
    { codigo_cuenca: '1033' , nombre_cuenca: 'Rio Bueno entre Rio Pilmaiquen y Rio Rahue' , region: 'X - XIV'},
    { codigo_cuenca: '1034' , nombre_cuenca: 'Rio Rahue hasta antes junta Rio Negro' , region: 'X - XIV'},
    { codigo_cuenca: '1035' , nombre_cuenca: 'Rio Negro' , region: 'X - XIV'},
    { codigo_cuenca: '1036' , nombre_cuenca: 'R. Rahue Bajo' , region: 'X - XIV'},
    { codigo_cuenca: '1037' , nombre_cuenca: 'R.  Bueno Bajo' , region: 'X - XIV'},

  { codigo_cuenca: "104" , nombre_cuenca: "Cuencas e Islas entre R.Bueno y R. Puelo" , region: "X" },
    { codigo_cuenca: '1040' , nombre_cuenca: 'Costeras entre Rio Bueno y Rio Maullin' , region: 'X'},
    { codigo_cuenca: '1041' , nombre_cuenca: 'Rio Maullin' , region: 'X'},
    { codigo_cuenca: '1042' , nombre_cuenca: 'Costeras e Islas entre Rio Maullin y Rio Chamiza' , region: 'X'},
    { codigo_cuenca: '1043' , nombre_cuenca: 'Rio Chamiza' , region: 'X'},
    { codigo_cuenca: '1044' , nombre_cuenca: 'Costeras entre Rio Chamiza y Rio Petrohue' , region: 'X'},
    { codigo_cuenca: '1045' , nombre_cuenca: 'Rio Petrohue' , region: 'X'},
    { codigo_cuenca: '1046' , nombre_cuenca: 'Costeras entre Rio Petrohue y Rio Puelo' , region: 'X'},

  { codigo_cuenca: "105" , nombre_cuenca: "Rio Puelo" , region: "X" },
    { codigo_cuenca: '1050' , nombre_cuenca: 'Rio Manso' , region: 'X'},
    { codigo_cuenca: '1051' , nombre_cuenca: 'R. Puelo Alto' , region: 'X'},
    { codigo_cuenca: '1052' , nombre_cuenca: 'R. Puelo Bajo' , region: 'X'},

  { codigo_cuenca: "106" , nombre_cuenca: "Costeras entre R.Puelo y R.Yelcho" , region: "X" },
    { codigo_cuenca: '1060' , nombre_cuenca: 'Costeras entre Rio Puelo y Punta Trentelhue' , region: 'X'},
    { codigo_cuenca: '1061' , nombre_cuenca: 'Costeras Entre Pta Tentelhue y Rio Negro (incl.)' , region: 'X'},
    { codigo_cuenca: '1062' , nombre_cuenca: 'Islas Pelada y Llancahue' , region: 'X'},
    { codigo_cuenca: '1063' , nombre_cuenca: 'Costeras entre Rio Negro y Rio Vodudahue' , region: 'X'},
    { codigo_cuenca: '1064' , nombre_cuenca: 'Rio Vodudahue' , region: 'X'},
    { codigo_cuenca: '1065' , nombre_cuenca: 'Peninsula Huequi' , region: 'X'},
    { codigo_cuenca: '1066' , nombre_cuenca: 'R. Re±ihue' , region: 'X'},
    { codigo_cuenca: '1067' , nombre_cuenca: 'Costeras Entre R.  Re±ihue y R. Negro' , region: 'X'},
    { codigo_cuenca: '1068' , nombre_cuenca: 'Costeras Entre R. Negro (incl.) y R. Yelcho' , region: 'X'},
    { codigo_cuenca: '1069' , nombre_cuenca: 'Archipielago Desertores' , region: 'X'},

  { codigo_cuenca: "107" , nombre_cuenca: "Rio Yelcho" , region: "X" },
    { codigo_cuenca: '1070' , nombre_cuenca: 'Rio Futaleufu' , region: 'X'},
    { codigo_cuenca: '1071' , nombre_cuenca: 'Rio Yelcho' , region: 'X'},

  { codigo_cuenca: "108" , nombre_cuenca: "Costeras entre R.Yelcho y limite Regional" , region: "X" },
    { codigo_cuenca: '1080' , nombre_cuenca: 'Costeras entre Rio Yelcho y Rio Corcovado' , region: 'X'},
    { codigo_cuenca: '1081' , nombre_cuenca: 'Rio Corcovado' , region: 'X'},
    { codigo_cuenca: '1082' , nombre_cuenca: 'Costeras entre Rio Corcovado y Limite Region' , region: 'X'},

  { codigo_cuenca: "109" , nombre_cuenca: "Islas Chiloe y Circundantes" , region: "X" },
    { codigo_cuenca: '1090' , nombre_cuenca: 'Isla Chiloe' , region: 'X'},
    { codigo_cuenca: '1091' , nombre_cuenca: 'Islas al Este de Quenchi' , region: 'X'},
    { codigo_cuenca: '1092' , nombre_cuenca: 'Islas entre Punta Chillidque y Punta Ahoni' , region: 'X'},
    { codigo_cuenca: '1093' , nombre_cuenca: 'Isla Tranqui' , region: 'X'},
    { codigo_cuenca: '1094' , nombre_cuenca: 'Islas frente a Quellon' , region: 'X'},
    { codigo_cuenca: '1095' , nombre_cuenca: 'Islas al Sur de Chiloe' , region: 'X'},
    { codigo_cuenca: '1096' , nombre_cuenca: 'Isla Guafo' , region: 'X'},

  { codigo_cuenca: "110" , nombre_cuenca: "Rio Palena y Costeras Limite Decima Region" , region: "X - XI" },
    { codigo_cuenca: '1100' , nombre_cuenca: 'Costeras entre Limite Decima Region y Rio Palena' , region: 'X - XI'},
    { codigo_cuenca: '1101' , nombre_cuenca: 'Lago Palena' , region: 'X - XI'},
    { codigo_cuenca: '1102' , nombre_cuenca: 'Rio Palena entre Frontera y Rio Rosselot' , region: 'X - XI'},
    { codigo_cuenca: '1103' , nombre_cuenca: 'Rio Rosselot' , region: 'X - XI'},
    { codigo_cuenca: '1104' , nombre_cuenca: 'R. Palena Bajo' , region: 'X - XI'},

  { codigo_cuenca: "111" , nombre_cuenca: "Costeras e Islas entre R.Palena y R.Aisen" , region: "XI" },
    { codigo_cuenca: '1110' , nombre_cuenca: 'Costeras entre R. Palena y R. Marchant (incl.)' , region: 'XI'},
    { codigo_cuenca: '1111' , nombre_cuenca: 'Isla Refugio' , region: 'XI'},
    { codigo_cuenca: '1112' , nombre_cuenca: 'Costeras entre Rio Marchant y Seno Ventisquero' , region: 'XI'},
    { codigo_cuenca: '1113' , nombre_cuenca: 'Costeras entre Seno Ventisquero y Rio Cisnes' , region: 'XI'},
    { codigo_cuenca: '1114' , nombre_cuenca: 'Rio Cisnes' , region: 'XI'},
    { codigo_cuenca: '1115' , nombre_cuenca: 'Costeras entre Rio Cisnes y Punta San Andres' , region: 'XI'},
    { codigo_cuenca: '1116' , nombre_cuenca: 'Islas entre Canales Jacal y Puyuhuapi' , region: 'XI'},
    { codigo_cuenca: '1117' , nombre_cuenca: 'Costeras entre Punta San Andres y Rio Aisen' , region: 'XI'},
    { codigo_cuenca: '1118' , nombre_cuenca: 'Islas al Este Canal Moraleda' , region: 'XI'},

  { codigo_cuenca: "112" , nombre_cuenca: "Archipielagos de Las Guaitecas y de los Chonos" , region: "XI" },
    { codigo_cuenca: '1120' , nombre_cuenca: 'Archipielago de las Guaitecas' , region: 'XI'},
    { codigo_cuenca: '1121' , nombre_cuenca: 'Islas al Oeste Canal Alanta y Norte Canal Simpson' , region: 'XI'},
    { codigo_cuenca: '1122' , nombre_cuenca: 'Islas al Este Canal Atlanta y Norte Canal Baeza' , region: 'XI'},
    { codigo_cuenca: '1123' , nombre_cuenca: 'Islas entre Canales Simpson, Baeza y King' , region: 'XI'},
    { codigo_cuenca: '1124' , nombre_cuenca: 'Islas entre Canales King, Perez Sur y Ninualac' , region: 'XI'},
    { codigo_cuenca: '1125' , nombre_cuenca: 'Islas entre Canales King, Perez Sur y Moraleda' , region: 'XI'},
    { codigo_cuenca: '1126' , nombre_cuenca: 'Islas entre Canales Ninualac, Pichirupa y Darwin' , region: 'XI'},
    { codigo_cuenca: '1127' , nombre_cuenca: 'Islas entre Canales Ninualac, Moraleda, Darwin y Pichirupa' , region: 'XI'},
    { codigo_cuenca: '1128' , nombre_cuenca: 'Islas entre Canales Darwin , Utarupa, Alejandro y Abandonados' , region: 'XI'},
    { codigo_cuenca: '1129' , nombre_cuenca: 'Islas entre Canales Darwin, Costa, Tres Cauces y Utarupa' , region: 'XI'},

  { codigo_cuenca: "113" , nombre_cuenca: "Rio Aisen" , region: "XI" },
    { codigo_cuenca: '1130' , nombre_cuenca: 'Rio Maniguales' , region: 'XI'},
    { codigo_cuenca: '1131' , nombre_cuenca: 'Rio Simpson' , region: 'XI'},
    { codigo_cuenca: '1132' , nombre_cuenca: 'Rio Aisen bajo Junta Maniguales-Simpson y Rio Riesco' , region: 'XI'},
    { codigo_cuenca: '1133' , nombre_cuenca: 'Rio Riesco' , region: 'XI'},
    { codigo_cuenca: '1134' , nombre_cuenca: 'Rio Aisen entre Rio Riesco y Desembocadura' , region: 'XI'},

  { codigo_cuenca: "114" , nombre_cuenca: "Costeras e Islas entre R Aisen y R Baker y Canal Gral. Martinez" , region: "XI" },
    { codigo_cuenca: '1140' , nombre_cuenca: 'Costeras entre R.  Aisen y R.  Huemules (incl.)' , region: 'XI'},
    { codigo_cuenca: '1141' , nombre_cuenca: 'Costeras entre Rio Huemules y Rio Exploradores' , region: 'XI'},
    { codigo_cuenca: '1142' , nombre_cuenca: 'Rio Exploradores' , region: 'XI'},
    { codigo_cuenca: '1143' , nombre_cuenca: 'Islas entre Fiordo Barros Arana y Golfo Elefantes' , region: 'XI'},
    { codigo_cuenca: '1144' , nombre_cuenca: 'Costera y Ventisqueros entre R.  Exploradores y Vent. Benito' , region: 'XI'},
    { codigo_cuenca: '1145' , nombre_cuenca: 'Peninsula de Taitao' , region: 'XI'},
    { codigo_cuenca: '1146' , nombre_cuenca: 'Campo de Hielo Norte' , region: 'XI'},
    { codigo_cuenca: '1147' , nombre_cuenca: 'Islas frente Ventisquero' , region: 'XI'},
    { codigo_cuenca: '1148' , nombre_cuenca: 'Costeras entre Fiordo julian y R. Baker' , region: 'XI'},

  { codigo_cuenca: "115" , nombre_cuenca: "Rio Baker" , region: "XI" },
    { codigo_cuenca: '1150' , nombre_cuenca: 'R. Iba±ez' , region: 'XI'},
    { codigo_cuenca: '1151' , nombre_cuenca: 'Vertiente N.  Lago J. Miguel Carrera (Exc.  R. Ibañez)' , region: 'XI'},
    { codigo_cuenca: '1152' , nombre_cuenca: 'Vertiente Sur Lago Jose Miguel Carrera' , region: 'XI'},
    { codigo_cuenca: '1153' , nombre_cuenca: 'R. Baker entre Desague L. J. M. Carrera y R. de La Colonia' , region: 'XI'},
    { codigo_cuenca: '1154' , nombre_cuenca: 'R. Baker entre arriba R. de La Colonia y Desembocadura' , region: 'XI'},

  { codigo_cuenca: "116" , nombre_cuenca: "Costeras e Islas entre R. Baker y R. Pascua" , region: "XI" },
    { codigo_cuenca: '1160' , nombre_cuenca: 'Costeras entre Rio Baker y Rio Bravo' , region: 'XI'},
    { codigo_cuenca: '1161' , nombre_cuenca: 'Rio Bravo' , region: 'XI'},
    { codigo_cuenca: '1162' , nombre_cuenca: 'Costeras entre Rio Bravo y Rio Pascua' , region: 'XI'},
    { codigo_cuenca: '1163' , nombre_cuenca: 'Islas entre Canal General Martinez y Canal Baker' , region: 'XI'},

  { codigo_cuenca: "117" , nombre_cuenca: "Rio Pascua" , region: "XI - XII" },
    { codigo_cuenca: '1170' , nombre_cuenca: "Lago O'Higgins" , region: 'XI - XII'},
    { codigo_cuenca: '1171' , nombre_cuenca: 'Rio Pascua' , region: 'XI - XII'},

  { codigo_cuenca: "118" , nombre_cuenca: "Costeras entre R. Pascua Limite Region. Archipielago Guayeco" , region: "XI" },
    { codigo_cuenca: '1180' , nombre_cuenca: 'Costeras entre Rio Pascua y Limite Region' , region: 'XI'},
    { codigo_cuenca: '1181' , nombre_cuenca: 'Islas entre Canal Mesier y Continente' , region: 'XI'},
    { codigo_cuenca: '1182' , nombre_cuenca: 'Islas Archipielago Guayeco al N. Estrecho Barbosa' , region: 'XI'},
    { codigo_cuenca: '1183' , nombre_cuenca: 'Isla Campana (Archipielago Guayeco)' , region: 'XI'},
    { codigo_cuenca: '1184' , nombre_cuenca: 'Isla Prat (Archipielago Guayeco)' , region: 'XI'},
    { codigo_cuenca: '1185' , nombre_cuenca: 'Isla Serrano (Archipielago Guayeco)' , region: 'XI'},
    { codigo_cuenca: '1186' , nombre_cuenca: 'Isla Patricio Lynch' , region: 'XI'},
    { codigo_cuenca: '1187' , nombre_cuenca: 'Otras Islas Archipielago Guayeco' , region: 'XI'},

  #{ codigo_cuenca: "119" , nombre_cuenca: "Cuenca del Pacífico" , region: "XI" },
    #{ codigo_cuenca: '1190' , nombre_cuenca: 'Rio de Las Cuatro Vueltas  (Archipielago)' , region: 'XI'},

  { codigo_cuenca: "120" , nombre_cuenca: "Costeras entre Limite Region y Seno Andrew" , region: "XI - XII" },
    { codigo_cuenca: '1200' , nombre_cuenca: 'Costeras del Canal Mesier Entre Limite Region y Peninsula Exmouth' , region: 'XI - XII'},
    { codigo_cuenca: '1201' , nombre_cuenca: 'Peninsula Exmuoth' , region: 'XI - XII'},
    { codigo_cuenca: '1202' , nombre_cuenca: 'Costeras del Fiordo Eyre (exc.  Peninsula Exmouth)' , region: 'XI - XII'},
    { codigo_cuenca: '1203' , nombre_cuenca: 'Costeras del NE. del Fiordo Falcon' , region: 'XI - XII'},
    { codigo_cuenca: '1204' , nombre_cuenca: 'Costeras entre Fiordo Falcon y Fiordo Penguin' , region: 'XI - XII'},
    { codigo_cuenca: '1205' , nombre_cuenca: 'Costeras entre Fiordo Penguin y Fiordo Europa' , region: 'XI - XII'},
    { codigo_cuenca: '1206' , nombre_cuenca: 'Peninsula Entre Fiordo Europa y Fiordo Guilardi' , region: 'XI - XII'},
    { codigo_cuenca: '1207' , nombre_cuenca: 'Peninsula Wilcok' , region: 'XI - XII'},
    { codigo_cuenca: '1208' , nombre_cuenca: 'Costeras entre fiordo Guilardi y Seno Andrew (exc.  Peninsula Wilcok)' , region: 'XI - XII'},

  { codigo_cuenca: "121" , nombre_cuenca: "Islas entre limite Region y Canal Ancho y Estrecho de la Concepcion" , region: "XII" },
    { codigo_cuenca: '1210' , nombre_cuenca: 'Islas al Poniente del Canal Fallos' , region: 'XII'},
    { codigo_cuenca: '1211' , nombre_cuenca: 'Islas entre Canal Fallos y la Isla Wellington' , region: 'XII'},
    { codigo_cuenca: '1212' , nombre_cuenca: 'Isla Wellington e Isla entre esta y el Oriente' , region: 'XII'},
    { codigo_cuenca: '1213' , nombre_cuenca: 'Islas al Poniente del Canal Picton' , region: 'XII'},
    { codigo_cuenca: '1214' , nombre_cuenca: 'Islas Poniente Est. Trinidad, Est. Concepcion y Canal Oeste' , region: 'XII'},
    { codigo_cuenca: '1215' , nombre_cuenca: 'Isla Duque de York' , region: 'XII'},

  { codigo_cuenca: "122" , nombre_cuenca: "Costeras entre Seno Andrew y R. Hollemberg e islas al oriente" , region: "XII" },
    { codigo_cuenca: '1220' , nombre_cuenca: 'Costeras entre Seno Andrew y Fiordo Calvo' , region: 'XII'},
    { codigo_cuenca: '1221' , nombre_cuenca: 'Costeras entre Fiordo Calvo y Fiordo Peel' , region: 'XII'},
    { codigo_cuenca: '1222' , nombre_cuenca: 'Peninsula entre Fiordo Peel y Paso Stewart' , region: 'XII'},
    { codigo_cuenca: '1223' , nombre_cuenca: 'Costeras e Islas entre fiordo Peel y Peninsula Sta.  Ines' , region: 'XII'},
    { codigo_cuenca: '1224' , nombre_cuenca: 'Peninsula Santa Ines e Islas Adyacentes' , region: 'XII'},
    { codigo_cuenca: '1225' , nombre_cuenca: 'Cordillera Sarmiento' , region: 'XII'},
    { codigo_cuenca: '1226' , nombre_cuenca: 'Peninsula Roca e Isla Diego Portales' , region: 'XII'},
    { codigo_cuenca: '1227' , nombre_cuenca: 'Costeras entre Peninsula Roca y Rio Serrano' , region: 'XII'},
    { codigo_cuenca: '1228' , nombre_cuenca: 'Rio Serrano' , region: 'XII'},
    { codigo_cuenca: '1229' , nombre_cuenca: 'Costeras entre Rio Serrano y Rio Hollenberg' , region: 'XII'},

  { codigo_cuenca: "123" , nombre_cuenca: "Islas entre Canales Concepcion, Sarmiento y E. de Magallanes" , region: "XII" },
    { codigo_cuenca: '1230' , nombre_cuenca: 'Islas Entre Fiordo Andrew, Canal Peel, Canal Inocentes y Estrecho de la Concepcion' , region: 'XII'},
    { codigo_cuenca: '1231' , nombre_cuenca: 'Islas Entre Canal Inocentes, Estrecho Sarmiento y Estrecho Guadalupe' , region: 'XII'},
    { codigo_cuenca: '1232' , nombre_cuenca: 'Islas Entre Estrecho Guadalupe, Paso Castro y Estrecho Nelson' , region: 'XII'},
    { codigo_cuenca: '1233' , nombre_cuenca: 'Islas Entre Paso Castro, Estrecho Sarmiento, Paso Victoria y Estrecho Smith' , region: 'XII'},
    { codigo_cuenca: '1234' , nombre_cuenca: 'Islas Entre Paso Castro, Estrecho Smith, Canal Bambach, Canal Señoret y Paso Uribe' , region: 'XII'},
    { codigo_cuenca: '1235' , nombre_cuenca: 'Islas Entre Paso Uribe, Canal Bertran y Canal Nogueira' , region: 'XII'},
    { codigo_cuenca: '1236' , nombre_cuenca: 'Islas al Poniente del Canal Nogueira' , region: 'XII'},
    { codigo_cuenca: '1237' , nombre_cuenca: "Canales entre Canal Bertran, Canal Se±oret y Canal O'Higginns" , region: 'XII'},
    { codigo_cuenca: '1238' , nombre_cuenca: "Islas entre Canal O'Higgins, Canal Bambach y Canal Smith" , region: 'XII'},

  { codigo_cuenca: "124" , nombre_cuenca: "Costeras e Islas entre R Hollemberg, Golfo Alte. Laguna Blanca" , region: "XII" },
    { codigo_cuenca: '1240' , nombre_cuenca: 'Costeras del Golfo Almirante Montt y Fiordo Obstruccion' , region: 'XII'},
    { codigo_cuenca: '1241' , nombre_cuenca: 'Peninsula Muñoz Gamero (Al N. Est. Excelsior)' , region: 'XII'},
    { codigo_cuenca: '1242' , nombre_cuenca: 'Peninsula Mu±oz Gamero (Al S. Est.  Excelsior)' , region: 'XII'},
    { codigo_cuenca: '1243' , nombre_cuenca: 'Islas Entre Canal Alte Martinez y Estrecho de Magallanes' , region: 'XII'},
    { codigo_cuenca: '1244' , nombre_cuenca: 'Isla Riesco' , region: 'XII'},
    { codigo_cuenca: '1245' , nombre_cuenca: 'Costeras Continentales del Seno Skyring' , region: 'XII'},

  { codigo_cuenca: "125" , nombre_cuenca: "Costeras entre Lag.  Blanca(inc), Seno Otway, canal Jeronimo y Magallanes" , region: "XII" },
    { codigo_cuenca: '1250' , nombre_cuenca: 'Laguna Blanca' , region: 'XII'},
    { codigo_cuenca: '1251' , nombre_cuenca: 'Costeras entre Laguna Blanca, Peninsula Brunswich y Santa Susana' , region: 'XII'},
    { codigo_cuenca: '1252' , nombre_cuenca: 'Rio Santa Susana' , region: 'XII'},
    { codigo_cuenca: '1253' , nombre_cuenca: 'Costeras entre R. Santa Susana y Chorrillo Kimiri Aike' , region: 'XII'},
    { codigo_cuenca: '1254' , nombre_cuenca: 'Costeras entre Chorrillo Kimiri Aike (incl.) y Ca±adon Grande (incl.)' , region: 'XII'},
    { codigo_cuenca: '1255' , nombre_cuenca: 'Costeras entre Cañadon Grande y Punta Dungeness' , region: 'XII'},
    { codigo_cuenca: '1256' , nombre_cuenca: 'Costeras Occidentales Peninsula Brunswick' , region: 'XII'},
    { codigo_cuenca: '1257' , nombre_cuenca: 'Costeras del Estrecho de Magallanes de la Peninsula Brunswick' , region: 'XII'},
    { codigo_cuenca: '1258' , nombre_cuenca: 'Costeras e Islas Orientales de la Peninsula Brunswick' , region: 'XII'},

  { codigo_cuenca: "126" , nombre_cuenca: "Vertiente del Atlantico" , region: "XII" },
    { codigo_cuenca: '1260' , nombre_cuenca: 'R. Rubens' , region: 'XII'},
    { codigo_cuenca: '1260' , nombre_cuenca: 'Vertiente del Atlantico' , region: 'XII'},
    { codigo_cuenca: '1261' , nombre_cuenca: 'Fronterizas entre Rio Rubens y Rio Penitente' , region: 'XII'},
    { codigo_cuenca: '1262' , nombre_cuenca: 'Rio Penitente' , region: 'XII'},
    { codigo_cuenca: '1263' , nombre_cuenca: 'Fronterizas entre R. Penitente y R. Gallegos Chico' , region: 'XII'},
    { codigo_cuenca: '1264' , nombre_cuenca: 'Rio Gallegos Chico' , region: 'XII'},
    { codigo_cuenca: '1265' , nombre_cuenca: 'Fronterizas entre Rio Gallegos Chico y Rio Cigike' , region: 'XII'},
    { codigo_cuenca: '1266' , nombre_cuenca: 'Rio Cigike y Rio de Los Pozuelos' , region: 'XII'},
    { codigo_cuenca: '1267' , nombre_cuenca: 'Ca±adon Seco' , region: 'XII'},
    { codigo_cuenca: '1268' , nombre_cuenca: 'Costeras Entre Ca±adon Seco y Ca±adon Grande' , region: 'XII'},

  { codigo_cuenca: "127" , nombre_cuenca: "Islas al Sur Estrecho de Magallanes" , region: "XII" },
    { codigo_cuenca: '1270' , nombre_cuenca: 'Isla Desolacion y adyacentes' , region: 'XII'},
    { codigo_cuenca: '1271' , nombre_cuenca: 'Isla Jacques' , region: 'XII'},
    { codigo_cuenca: '1272' , nombre_cuenca: 'Islas al S. del Seno Dyvenor y Canal Abra al O. I.  Sta Ines' , region: 'XII'},
    { codigo_cuenca: '1273' , nombre_cuenca: 'Isla Santa Ines y Carlos III' , region: 'XII'},
    { codigo_cuenca: '1274' , nombre_cuenca: 'Islas al S. Isla Sta Ines y al O. Canal Barbara y Canal Cockburn' , region: 'XII'},
    { codigo_cuenca: '1275' , nombre_cuenca: 'Islas Clarence y adyacentes' , region: 'XII'},
    { codigo_cuenca: '1276' , nombre_cuenca: 'Isla Capitan Aracena y adyacentes' , region: 'XII'},

  { codigo_cuenca: "128" , nombre_cuenca: "Tierra del Fuego" , region: "XII" },
    { codigo_cuenca: '1280' , nombre_cuenca: 'Costeras del Estrecho Magallanes, entre Frontera y Cabo Monmouth' , region: 'XII'},
    { codigo_cuenca: '1281' , nombre_cuenca: 'Costeras Bahia Inutil (entre Cabo Monmouth y Cabo Nose)' , region: 'XII'},
    { codigo_cuenca: '1282' , nombre_cuenca: 'Costeras entre Cabo Nose y R. Azopardo (incl.)' , region: 'XII'},
    { codigo_cuenca: '1283' , nombre_cuenca: 'Costeras entre R. Azopardo y Seno Serrano' , region: 'XII'},
    { codigo_cuenca: '1284' , nombre_cuenca: 'Peninsula Entre Senos Serrano y Ventisqueros' , region: 'XII'},
    { codigo_cuenca: '1285' , nombre_cuenca: 'Costeras Canal Beagle (entre Seno Ventisquero y Frontera)' , region: 'XII'},
    { codigo_cuenca: '1286' , nombre_cuenca: 'Cuencas Atlanticas hasta Frontera entre Arroyo Alfa (incl.) y Afluentes R. Grande (Arg.)' , region: 'XII'},
    { codigo_cuenca: '1287' , nombre_cuenca: 'Afluentes Rio Grande y Cuencas Cerradas' , region: 'XII'},
    { codigo_cuenca: '1288' , nombre_cuenca: 'Cuencas Compartidas al Sur R. Azopardo y Cuencas Cerradas' , region: 'XII'},
    { codigo_cuenca: '1289' , nombre_cuenca: 'Islas al Sur de Tierra del Fuego y Canal Beagle' , region: 'XII'},

  { codigo_cuenca: "129" , nombre_cuenca: "Islas al sur del Canal Beagle y Territorio Antartico" , region: "XII" },
    { codigo_cuenca: '1290' , nombre_cuenca: 'Islas Londonberry y Adyacentes, al Sur de Canal Pomar y Oeste de Bahia Cook' , region: 'XII'},
    { codigo_cuenca: '1291' , nombre_cuenca: 'Islas entre Brazos del Canal Beagle, al NE de Bahia Cook' , region: 'XII'},
    { codigo_cuenca: '1292' , nombre_cuenca: 'Isla Hoste y adyacentes' , region: 'XII'},
    { codigo_cuenca: '1293' , nombre_cuenca: 'Islas Navarino y Gable' , region: 'XII'},
    { codigo_cuenca: '1294' , nombre_cuenca: 'Islas Nueva, Picton, Lennox, Evout y otras' , region: 'XII'},
    { codigo_cuenca: '1295' , nombre_cuenca: "Islas Wallaston, L'Hermite, Hornos y otras" , region: 'XII'},
    { codigo_cuenca: '1296' , nombre_cuenca: 'Islas Diego Ramirez' , region: 'XII'}
]

cuencas_y_subcuencas.each do |attrs|
  Cuenca.find_or_create_by(attrs)
end