default: &default
  adapter: postgresql
  encoding: unicode
  timeout: 5000
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("LOCALHOST_PSQL_SERVER") %>
  username: <%= ENV.fetch("LOCALHOST_PSQL_USERNAME") %>
  password: <%= ENV.fetch("LOCALHOST_PSQL_PASSWORD") %>
  template: template0
  schema_search_path: "public, admin"


timeout: 50000  

development:
  <<: *default
  # database: ascc_development
  # database: ascc_staging
  database: ascc_qa_daniel
  # database: ascc_qa
test:
  <<: *default
  database: ascc_test__up

production:
  <<: *default
  database: ascc_prod

staging:
  <<: *default
  database: ascc_staging

external_fpl_db:
  <<: *default
  host: <%= ENV.fetch("EXTERNAL_PSQL_SERVER") {} %>
  username: <%= ENV.fetch("EXTERNAL_PSQL_USERNAME") {} %>
  password: <%= ENV.fetch("EXTERNAL_PSQL_PASSWORD") {} %>
  template: template0
  schema_search_path: "public"
  database: ascc_dump
