development:
  adapter: postgresql
  encoding: unicode
  timeout: 5000
  pool: 5
  host: localhost
  username: postgres
  password: 2802Tete99
  template: template0
  schema_search_path: "public, admin"
  database: bd_accion

test:
  adapter: postgresql
  encoding: unicode
  timeout: 5000
  pool: 5
  host: localhost
  username: guillo10
  template: template0
  schema_search_path: "public, admin"
  database: ascc_test

staging:
  adapter: postgresql
  encoding: unicode
  timeout: 5000
  pool: 5
  host: localhost
  username: guillo10
  template: template0
  schema_search_path: "public, admin"
  database: bd_dev_accion

production:
  adapter: postgresql
  encoding: unicode
  timeout: 5000
  pool: 5
  host: localhost
  username: guillo10
  template: template0
  schema_search_path: "public, admin"
  database: bd_accion

external_fpl_db:
  adapter: postgresql
  encoding: unicode
  timeout: 5000
  pool: 5
  host: localhost
  username: postgres
  password: postgres
  template: template0
  schema_search_path: "public"
  database: cpl_desarrollo_dbfpl
