default: &defaults
  adapter: postgresql
  encoding: unicode
  timeout: 5000
  pool: 5
  host: localhost
  username: guillo10
  template: template0
  schema_search_path: "public, admin"

development:
  <<: *defaults
  database: bd_accion

test:
  <<: *defaults
  database: ascc_test

staging:
  <<: *defaults
  database: bd_dev_accion

production:
  <<: *defaults
  database: bd_accion

external_fpl_db:
  <<: *defaults
  host: localhost
  username: postgres
  password: postgres
  template: template0
  schema_search_path: "public"
  database: cpl_desarrollo_dbfpl
