development:
  adapter: postgresql
  encoding: unicode
  timeout: 5000
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("LOCALHOST_PSQL_SERVER") %>
  username: <%= ENV.fetch("LOCALHOST_PSQL_USERNAME") %>
  password: <%= ENV.fetch("LOCALHOST_PSQL_PASSWORD") %>
  template: template0
  schema_search_path: "public, admin"
  database: ascc_development

test:
  adapter: postgresql
  encoding: unicode
  timeout: 5000
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("LOCALHOST_PSQL_SERVER") %>
  username: <%= ENV.fetch("LOCALHOST_PSQL_USERNAME") %>
  password: <%= ENV.fetch("LOCALHOST_PSQL_PASSWORD") %>
  template: template0
  schema_search_path: "public, admin"
  database: ascc_test

production:
  adapter: postgresql
  encoding: unicode
  timeout: 5000
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("LOCALHOST_PSQL_SERVER") %>
  username: <%= ENV.fetch("LOCALHOST_PSQL_USERNAME") %>
  password: <%= ENV.fetch("LOCALHOST_PSQL_PASSWORD") %>
  template: template0
  schema_search_path: "public, admin"
  database: ascc_prod

external_fpl_db:
  adapter: postgresql
  encoding: unicode
  timeout: 5000
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("LOCALHOST_PSQL_SERVER") %>
  username: <%= ENV.fetch("LOCALHOST_PSQL_USERNAME") %>
  password: <%= ENV.fetch("LOCALHOST_PSQL_PASSWORD") %>
  template: template0
  schema_search_path: "public"
  database: ascc_prod

