#
# This file configures the New Relic Agent.  New Relic monitors Ruby, Java,
# .NET, PHP, Python, Node, and Go applications with deep visibility and low
# overhead.  For more information, visit www.newrelic.com.
#
# Generated June 3, 2021
#
# This configuration file is custom generated for NewRelic Administration
#
# For full documentation of agent configuration options, please refer to
# https://docs.newrelic.com/docs/agents/ruby-agent/installation-configuration/ruby-agent-configuration

development:
  # Required license key associated with your New Relic account.
  license_key: ENV['NEW_RELIC_LICENSE_KEY']

  # Your application name. Renaming here affects where data displays in New Relic.
  app_name: ASCC - Accion (Development)

  agent_enabled: <%= ENV['ENABLE_NEW_RELIC'] %>

  distributed_tracing:
    enabled: true

  # Logging level for log/newrelic_agent.log
  log_level: info

test:
  # Required license key associated with your New Relic account.
  license_key: ENV['NEW_RELIC_LICENSE_KEY']

  # Your application name.
  app_name: ASCC - Accion (Test)

  # It doesn't make sense to report to New Relic from automated test runs.
  monitor_mode: false

  agent_enabled: <%= ENV['ENABLE_NEW_RELIC'] %>

  distributed_tracing:
    enabled: true

  # Logging level for log/newrelic_agent.log
  log_level: info

staging:
  # Required license key associated with your New Relic account.
  license_key: ENV['NEW_RELIC_LICENSE_KEY']

  # Your application name.
  app_name: ASCC - Accion (Staging)

  agent_enabled: <%= ENV['ENABLE_NEW_RELIC'] %>

  distributed_tracing:
    enabled: true

  # Logging level for log/newrelic_agent.log
  log_level: info

production:
  # Required license key associated with your New Relic account.
  license_key: ENV['NEW_RELIC_LICENSE_KEY']

  # Your application name.
  app_name: ASCC - Accion - prod

  agent_enabled: <%= ENV['ENABLE_NEW_RELIC'] %>

  distributed_tracing:
    enabled: true

  # Logging level for log/newrelic_agent.log
  log_level: info


