development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

test:
  secret_key_base: c8f985fe9365b722e38c45d00b8cea0076f788d3976d0cdbde13ee5e1401d804e4db0e87cf483b7dd7e106bcf61af4c10b6fdb0c357bce907cb0f1138203ba56

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  # DZC 2018-11-26 11:37:00 se agrega llave secreta de google via variable de entorno
  google_api_key: <%= ENV["GOOGLE_API_KEY"] %>
