class CreateClasificaciones < ActiveRecord::Migration[5.1]
  def change
    create_table :clasificaciones do |t|
      t.integer :clasificacion_id
      t.string :nombre, null: false
      t.text :descripcion, null: false
      t.text :referencia, null: false
      t.boolean :es_meta, null: false, default: false
    end
    add_foreign_key :clasificaciones, :clasificaciones
  end
  
  def migrate(direction)
    super
    if direction == :up
      query
    end
  end

  def query
    execute <<-SQL
      INSERT INTO "clasificaciones" ("id", "clasificacion_id", "nombre", "descripcion", "referencia", "es_meta") VALUES
        (1, NULL, 'Gestión de la Energía',  'Clasificador de Acciones generales referidas a Gestión de la Energía, de preferencia utilizar otra clasificación más específica.', '07.02, 07.03 ODS', 't'),
        (2, 1,  'ERNC', 'Aumentar considerablemente la proporción de energía renovable en el conjunto de fuentes energéticas.', '07.02 ODS',  'f'),
        (3, NULL, 'Eficiencia Energética',  'Aumentar la eficiencia energética.', '07.03 ODS',  'f'),
        (4, NULL, 'Eficiencia Productiva',  'Lograr niveles más elevados de productividad económica mediante la diversificación, la modernización tecnológica y la innovación, entre otras cosas, centrándose en los sectores con gran valor añadido y un uso intensivo de la mano de obra.', '08.02 ODS',  'f'),
        (5, NULL, 'Prevención de Desastres y Resiliencia Climática',  'Fomentar la resiliencia, principalmente de los pobres y las personas que se encuentran en situaciones de vulnerabilidad y reducir su exposición y vulnerabilidad a los fenómenos extremos relacionados con el clima y otras perturbaciones y desastres económicos, sociales y ambientales.', '01.05, 11.05, 13.01 ODS',  'f'),
        (6, NULL, 'Incremento de la Productividad e Ingresos Productores Agrícolas',  'Incremento de la productividad agrícola y los ingresos de los productores de alimentos en pequeña escala, en particular las mujeres, los pueblos indígenas, los agricultores familiares, los ganaderos y los pescadores, entre otras cosas mediante un acceso seguro y equitativo a las tierras, a otros recursos e insumos de producción y a los conocimientos, los servicios financieros, los mercados y las oportunidades para añadir valor y obtener empleos no agrícolas.', '02.03 ODS',  'f'),
        (7, NULL, 'Agricultura Sostenible', 'Asegurar la sostenibilidad de los sistemas de producción de alimentos y aplicar prácticas agrícolas resilientes que aumenten la productividad y la producción, contribuyan al mantenimiento de los ecosistemas, fortalezcan la capacidad de adaptación al cambio climático, los fenómenos meteorológicos extremos, las sequías, las inundaciones y otros desastres, y mejoren progresivamente la calidad de la tierra y el suelo.',  '02.04 ODS',  'f'),
        (8, NULL, 'Biodiversidad Agrícola', 'Mantener la diversidad genética de las semillas, las plantas cultivadas y los animales de granja y domesticados y sus correspondientes especies silvestres, entre otras cosas mediante una buena gestión y diversificación de los bancos de semillas y plantas a nivel nacional, regional e internacional, y promover el acceso a los beneficios que se deriven de la utilización de los recursos genéticos y los conocimientos tradicionales conexos y su distribución justa y equitativa, según lo convenido internacionalmente.', '02.05 ODS',  'f'),
        (9, NULL, 'Seguridad sanitaria',  'Poner fin a las epidemias del SIDA, la tuberculosis, la malaria y las enfermedades tropicales desatendidas y combatir la hepatitis, las enfermedades transmitidas por el agua y otras enfermedades transmisibles.',  '03.03 ODS',  'f'),
        (10,  NULL, 'Reducción de mortalidad prematura',  'Reducir en la mortalidad prematura por enfermedades no transmisibles mediante su prevención y tratamiento, y promover la salud mental y el bienestar', '03.04 ODS',  'f'),
        (11,  NULL, 'Reducción y Manejo de Emisiones de Contaminantes y Sustancias Tóxicas',  'Reducir considerablemente el número de muertes y enfermedades causadas por productos químicos peligrosos y por la polución y contaminación del aire, el agua y el suelo.', '03.09, 11.06, 12.04 ODS',  'f'),
        (12,  NULL, 'Educación para la Sustentabilidad y Cambio Climático', 'Asegurar que todos los alumnos adquieran los conocimientos teóricos y prácticos necesarios para promover el desarrollo sostenible, entre otras cosas mediante la educación para el desarrollo sostenible y los estilos de vida sostenibles, los derechos humanos, la igualdad de género, la promoción de una cultura de paz y no violencia, la ciudadanía mundial y la valoración de la diversidad cultural y la contribución de la cultura al desarrollo sostenible; además de educar respecto a la mitigación del cambio climático y la adaptación a él.', '04.07, 13.03, 12.08 ODS',  'f'),
        (13,  NULL, 'Acoso, Discriminación y Maltrato', 'Eliminar todas las formas de discriminación, violencia contra todas las mujeres y las niñas en los ámbitos público y privado, incluidas la trata y la explotación sexual y otros tipos de explotación.', '05.01, 05.02, 08.05, 08.08, 10.03, 10.07, 16.b ODS', 'f'),
        (14,  NULL, 'Equidad de Género',  'Asegurar la participación plena y efectiva de las mujeres y la igualdad de oportunidades de liderazgo a todos los niveles decisorios en la vida política, económica y pública',  '05.05, 05.c ODS',  'f'),
        (15,  NULL, 'Reducción y Manejo de Contaminantes y Sustancias Tóxicas en el Agua',  'Mejorar la calidad del agua reduciendo la contaminación, eliminando el vertimiento y minimizando la emisión de productos químicos y materiales peligrosos, reduciendo a la mitad el porcentaje de aguas residuales sin tratar y aumentando considerablemente el reciclado y la reutilización sin riesgos a nivel mundial.',  '06.03, 11.06 ODS', 'f'),
        (16,  NULL, 'Eficiencia y estrés hídrico',  'Aumentar considerablemente el uso eficiente de los recursos hídricos en todos los sectores y asegurar la sostenibilidad de la extracción y el abastecimiento de agua dulce para hacer frente a la escasez de agua y reducir considerablemente el número de personas que sufren falta de agua.',  '06.04 ODS',  'f'),
        (17,  NULL, 'Gestión Integrada de Cuencas', 'Implementar la gestión integrada de los recursos hídricos a todos los niveles, incluso mediante la cooperación transfronteriza, según proceda.', '06.05 ODS',  'f'),
        (18,  NULL, 'Conservación y Recuperación Ecosistema Cuenca',  'Cambio en la extensión de los ecosistemas relacionados con el agua con el paso del tiempo.', '06.06 ODS',  'f'),
        (19,  NULL, 'Generación de Capacidades en Gestión del Agua',  'Cooperación y apoyo prestado para la creación de capacidad en actividades y programas relativos al agua y el saneamiento, como los de captación de agua, desalinización, uso eficiente de los recursos hídricos, tratamiento de aguas residuales, reciclado y tecnologías de reutilización', '06.a ODS', 'f'),
        (20,  NULL, 'Participación de Comunidades en Manejo de Cuencas',  'Proporción de dependencias administrativas locales que han establecido políticas y procedimientos operacionales para la participación de las comunidades locales en la gestión del agua y el saneamiento.',  '06.b ODS', 'f'),
        (21,  NULL, 'Formalización y Regularización', 'Promover políticas orientadas al desarrollo que apoyen las actividades productivas, la creación de puestos de trabajo decentes, el emprendimiento, la creatividad y la innovación, y fomentar la formalización y el crecimiento de las microempresas y las pequeñas y medianas empresas.', '08.03 ODS (Foco cumplimiento normativo)',  'f'),
        (22,  NULL, 'Acceso a Financiamiento',  'Adoptar y aplicar sistemas de promoción de las inversiones y acceso a financiamiento en favor de MiPYMES.',  '08.03, 09.03, 17.05 ODS',  'f'),
        (23,  NULL, 'Gestión Huella Material',  'Uso eficiente de recursos en toda la cadena productiva, con el efecto de reducir la cantidad de materia prima requerida para producir una unidad de producto.',  '08.04 ODS, 12.02 ODS', 'f'),
        (24,  NULL, 'Higiene y seguridad laboral',  'Proteger los derechos laborales y promover un entorno de trabajo seguro y sin riesgos para todos los trabajadores, incluidos los trabajadores migrantes, en particular las mujeres migrantes y las personas con empleos precarios.', '08.08 ODS',  'f'),
        (25,  NULL, 'Turismo sostenible', 'Elaborar y aplicar instrumentos para vigilar los efectos en el desarrollo sostenible, a fin de lograr un turismo sostenible que cree puestos de trabajo y promueva la cultura y los productos locales.', '08.09, 12.b ODS',  'f'),
        (26,  NULL, 'Fomento al Empleo Joven',  'Desarrollar y poner en marcha una estrategia mundial para el empleo de los jóvenes y aplicar el Pacto Mundial para el Empleo de la Organización Internacional del Trabajo.', '08.06, 08.b ODS',  'f'),
        (27,  NULL, 'Incremento de Valor Manufactura',  'Promover una industrialización inclusiva y sostenible, y aumentar significativamente la contribución de la industria al empleo y al producto interno bruto, de acuerdo con las circunstancias nacionales.',  '09.02 ODS',  'f'),
        (28,  NULL, 'Mitigación Cambio Climático',  'Modernizar la infraestructura y reconvertir las industrias para que sean sostenibles, utilizando los recursos con mayor eficacia y promoviendo la adopción de tecnologías y procesos industriales limpios y ambientalmente racionales, y logrando que  las empresas tomen medidas de acuerdo con sus capacidades respectivas', '09.04 ODS',  'f'),
        (29,  NULL, 'Paquetes Tecnológicos e Investigación',  'Apoyo a la creación de capacidad en materia de ciencia, tecnología e innovación y aumentar la utilización de tecnologías instrumentales, en particular la tecnología de la información y las comunicaciones.', '09.05, 09.b, 12.a, 14.a, 17.08, 17.07',  'f'),
        (30,  NULL, 'Inclusión',  'Potenciar y promover la inclusión social, económica y política de todas las personas, independientemente de su edad, sexo, discapacidad, raza, etnia, origen, religión o situación económica u otra condición.', '10.02 ODS',  'f'),
        (31,  NULL, 'Protección del Patrimonio Cultural y Natural', 'Realizar esfuerzos para proteger y salvaguardar el patrimonio cultural y natural de Chile',  '11.04 ODS',  'f'),
        (32,  NULL, 'Reducción de Emisiones de Sustancias Agotadoras de la Capa de Ozono',  'Reducir las emisiones de sustancias agotadoras de la capa de ozono', 'Protocolo de Montreal',  'f'),
        (33,  NULL, 'Bienestar Animal', 'Acciones que mejoran el bienestar y eliminan o disminuyen el sufrimiento de animales utilizados en la producción de carne o productos derivados.', 'Declaración Universal de Bienestar Animal apoyada por Chile desde 2010 (aún no es tratado internacional)', 'f'),
        (34,  NULL, 'Prevenir y Reducir Contaminación Marina',  'Prevenir y reducir significativamente la contaminación marina de todo tipo, en particular la producida por actividades realizadas en tierra, incluidos los detritos marinos y la polución por nutrientes.',  '11.06, 14.01 ODS', 'f'),
        (35,  NULL, 'Acceso a áreas verdes y espacios públicos seguros, inclusivos y accesibles', 'Proporcionar acceso a zonas verdes y espacios públicos seguros, inclusivos y accesibles, en particular para las mujeres y los niños, las personas de edad y las personas con discapacidad.', '11.07 ODS',  'f'),
        (36,  NULL, 'Construcción Sustentable', 'Proporcionar apoyo, incluso mediante asistencia financiera y técnica, para que la construcción de edificios sostenibles y resilientes utilizando materiales locales.', '11.c ODS', 'f'),
        (37,  NULL, 'Gestión Huella Ambiental', 'Producción y consumo eficientes de los recursos en toda la cadena productiva, procurando desvincular el crecimiento económico de la degradación del medio ambiente.',  '12.02 ODS',  'f'),
        (38,  NULL, 'Desperdicios de alimentos',  'Reducir el desperdicio de alimentos per cápita en la venta al por menor y a nivel de los consumidores y reducir las pérdidas de alimentos en las cadenas de producción y suministro, incluidas las pérdidas posteriores a la cosecha.',  '13.03 ODS',  'f'),
        (39,  NULL, 'Transparencia y acceso público a la información ', 'Garantizar y dar acceso público a la información.',  '12.06, 16.06, 16.10 ODS',  'f'),
        (40,  NULL, 'Instituciones y Servicios Públicos de Calidad',  'Instituciones eficaces que rinden cuentas y cuyos usuarios poseen una experiencia satisfactoria.', '16.06 ODS',  'f'),
        (41,  NULL, 'Compras Públicas Sostenibles', 'Promover prácticas de adquisición pública que sean sostenibles, de conformidad con las políticas y prioridades nacionales.', '12.07 ODS',  'f'),
        (42,  NULL, 'Adaptación', 'Fortalecer la resiliencia y capacidad de Adaptación al Déficit hídrico, desertificación, modificaciones de patrones climáticos con efecto sobre cultivos y especies.', '13.01, 13.02 ODS', 'f'),
        (43,  NULL, 'Conservación y Uso Sostenible Áreas Marinas',  'Gestionar y proteger sosteniblemente los ecosistemas marinos y costeros para evitar efectos adversos importantes, incluso fortaleciendo su resiliencia, y adoptar medidas para restaurarlos a fin de restablecer la salud y la productividad del océano.', '14.02, 14.04 ODS', 'f'),
        (44,  NULL, 'Prevenir y Reducir Acidificación', 'Minimizar y abordar los efectos de la acidificación de los océanos, incluso mediante una mayor cooperación científica a todos los niveles.', '14.03 ODS',  'f'),
        (45,  NULL, 'Transporte Marítimo Sostenible', 'Mejorar la conservación y el uso sostenible de los océanos mediante cambios en la practicas y tecnologías de transporte entre continentes.', ' 14.04, 14.c ODS', 'f'),
        (46,  NULL, 'Conservación y Uso Sostenible de Cuencas', 'Conservación, el restablecimiento y el uso sostenible de los ecosistemas terrestres y los ecosistemas interiores de agua dulce y sus servicios, en particular los bosques, los humedales, las montañas y las zonas áridas, en consonancia con las obligaciones contraídas en virtud de acuerdos internacionales.', '15.01, 15.04 ODS', 'f'),
        (47,  NULL, 'Conservación de la biodiversidad terrestre', 'Adopción de medidas urgentes y significativas para reducir la degradación de los hábitats naturales, detener la pérdida de biodiversidad y proteger las especies amenazadas y evitar su extinción.', '15.05 ODS',  'f'),
        (48,  NULL, 'Acceso a recursos genéticos',  'Promover la participación justa y equitativa en los beneficios derivados de la utilización de los recursos genéticos y promover el acceso adecuado a esos recursos.',  '15.06 ODS ', 'f'),
        (49,  NULL, 'Evitar Introducción de Especies Exóticas', 'Adoptar medidas para prevenir la introducción de especies exóticas invasoras y reducir significativamente sus efectos en los ecosistemas terrestres y acuáticos y controlar o erradicar las especies prioritarias',  '15.08 ODS',  'f'),
        (50,  NULL, 'Eliminar o Reducir Corrupción',  'Reducir considerablemente la corrupción y el soborno en todas sus formas', '16.05 ODS',  'f'),
        (51,  NULL, 'Adopción de decisiones inclusivas',  'Garantizar la adopción en todos los niveles de decisiones inclusivas, participativas y representativas que respondan a las necesidades.',  '16.07 ODS',  'f'),
        (52,  NULL, 'Mejorar Exportaciones',  'Aumentar las exportaciones y evitar riesgo de sanciones en mercados de destino por malas prácticas operacionales.',  '17.11 ODS',  'f'),
        (53,  NULL, 'Coherencia Aplicación Políticas',  'Mejorar la coherencia de las políticas y acciones territoriales/sectoriales para el desarrollo sostenible',  '17.14 ODS',  'f'),
        (54,  NULL, 'Levantar Datos', 'Iniciativas para elaborar indicadores que permitan medir los progresos en materia de desarrollo sostenible y complementen el producto interno bruto, y apoyar la creación de capacidad estadística, así como la cantidad de participantes que cumple con estas iniciativas.',  '17.16, 17.19 ODS', 'f'),
        (55,  NULL, 'Alianza Pública Privada',  'Fomentar y promover la constitución de alianzas eficaces en las esferas pública, público-privada y de la sociedad civil, aprovechando la experiencia y las estrategias de obtención de recursos de las alianzas',  '17.17 ODS',  'f'),
        (56,  NULL, 'Forestación, Reforestación, Gestión Forestal Sostenible, Recuperación y Conservación', 'Acciones de Forestación, Reforestación, Gestión Forestal Sostenible,Recuperación de suelos degradados y Conservación', '15.02, 15.03 y 15.b ODS',  'f');
      
      SELECT SETVAL('clasificaciones_id_seq', (SELECT MAX(id) FROM clasificaciones));
    SQL
  end
end
