class AgregaTimeStamps < ActiveRecord::Migration[5.1]
  def change
  	add_timestamps :accion_clasificaciones, null: true
  	add_timestamps :accion_relacionadas, null: true
  	add_timestamps :acciones, null: true  	
  	add_timestamps :actividad_economicas, null: true
  	add_timestamps :actividad_items, null: true
  	add_timestamps :actividad_por_lineas, null: true
  	add_timestamps :actividades, null: true
  	add_timestamps :alcances, null: true
  	add_timestamps :cargos, null: true
  	add_timestamps :centro_de_costos, null: true
  	add_timestamps :clasificaciones, null: true
  	add_timestamps :contribuyentes, null: true
  	add_timestamps :dato_anual_contribuyentes, null: true  	
  	add_timestamps :descargable_tareas, null: true    
  	add_timestamps :documento_diagnosticos, null: true      	
  	add_timestamps :ejecucion_presupuestarias, null: true      		
  	add_timestamps :estado_admisibilidades, null: true      
  	add_timestamps :estado_documento_garantias, null: true   
  	add_timestamps :estado_rendiciones, null: true   
  	add_timestamps :estado_tarea_pendientes, null: true   
  	add_timestamps :etapas, null: true   
  	add_timestamps :feriados, null: true  
  	add_timestamps :flujo_tareas, null: true  
  	add_timestamps :glosas, null: true  
  	add_timestamps :hito_de_prensa_instrumentos, null: true  
   	add_timestamps :hito_de_prensa_responsables, null: true   	
   	add_timestamps :instrumentos, null: true   
   	add_timestamps :lugar_coordenadas, null: true   
   	add_timestamps :materia_sustancia_clasificaciones, null: true      	
   	add_timestamps :materia_sustancias, null: true  
   	add_timestamps :modalidades, null: true   
   	add_timestamps :persona_cargos, null: true   
   	add_timestamps :proveedor_tipo_proveedores, null: true  
   	add_timestamps :provincias, null: true  
   	add_timestamps :proyecto_actividades, null: true
   	add_timestamps :proyecto_pagos, null: true   	
   	add_timestamps :rango_venta_contribuyentes, null: true      	
   	add_timestamps :regiones, null: true      	
   	add_timestamps :responsables, null: true  
   	add_timestamps :roles, null: true  
   	add_timestamps :tamano_contribuyentes, null: true  
   	add_timestamps :tareas, null: true  
   	add_timestamps :tipo_aportes, null: true  
   	add_timestamps :tipo_comentarios, null: true  
   	add_timestamps :tipo_contribuyentes, null: true  
   	add_timestamps :tipo_de_medios, null: true  
   	add_timestamps :tipo_documento_diagnosticos, null: true  
   	add_timestamps :tipo_documento_garantias, null: true  
   	add_timestamps :tipo_instrumentos, null: true  
   	add_timestamps :tipo_proveedores, null: true    
   	add_timestamps :variables, null: true    	

  	# rellena los registros preexistentes
	  ahora = DateTime.now
	  AccionClasificacion.update_all(created_at: ahora, updated_at: ahora)
		AccionRelacionada.update_all(created_at: ahora, updated_at: ahora)
		Accion.update_all(created_at: ahora, updated_at: ahora)		
		ActividadEconomica.update_all(created_at: ahora, updated_at: ahora)
		ActividadItem.update_all(created_at: ahora, updated_at: ahora)
		ActividadPorLinea.update_all(created_at: ahora, updated_at: ahora)
		Actividad.update_all(created_at: ahora, updated_at: ahora)
		Alcance.update_all(created_at: ahora, updated_at: ahora)
		Cargo.update_all(created_at: ahora, updated_at: ahora)
		CentroDeCosto.update_all(created_at: ahora, updated_at: ahora)
		Clasificacion.update_all(created_at: ahora, updated_at: ahora)
		Contribuyente.update_all(created_at: ahora, updated_at: ahora)
		DatoAnualContribuyente.update_all(created_at: ahora, updated_at: ahora)			
		DescargableTarea.update_all(created_at: ahora, updated_at: ahora)		
		DocumentoDiagnostico.update_all(created_at: ahora, updated_at: ahora)					
		EjecucionPresupuestaria.update_all(created_at: ahora, updated_at: ahora)			
		EstadoAdmisibilidad.update_all(created_at: ahora, updated_at: ahora)	
		EstadoDocumentoGarantia.update_all(created_at: ahora, updated_at: ahora)	
		EstadoRendicion.update_all(created_at: ahora, updated_at: ahora)	
		EstadoTareaPendiente.update_all(created_at: ahora, updated_at: ahora)	
		Etapa.update_all(created_at: ahora, updated_at: ahora)	
		Feriado.update_all(created_at: ahora, updated_at: ahora)	
		FlujoTarea.update_all(created_at: ahora, updated_at: ahora)
		Glosa.update_all(created_at: ahora, updated_at: ahora)
		HitoDePrensaInstrumento.update_all(created_at: ahora, updated_at: ahora)
		HitoDePrensaResponsable.update_all(created_at: ahora, updated_at: ahora)
		Instrumento.update_all(created_at: ahora, updated_at: ahora)	
		LugarCoordenada.update_all(created_at: ahora, updated_at: ahora)	
		MateriaSustanciaClasificacion.update_all(created_at: ahora, updated_at: ahora)	
		MateriaSustancia.update_all(created_at: ahora, updated_at: ahora)	
		Modalidad.update_all(created_at: ahora, updated_at: ahora)	
		PersonaCargo.update_all(created_at: ahora, updated_at: ahora)	
		ProveedorTipoProveedor.update_all(created_at: ahora, updated_at: ahora)	
		Provincia.update_all(created_at: ahora, updated_at: ahora)	
		ProyectoActividad.update_all(created_at: ahora, updated_at: ahora)	
		ProyectoPago.update_all(created_at: ahora, updated_at: ahora)			
		RangoVentaContribuyente.update_all(created_at: ahora, updated_at: ahora)		
		Region.update_all(created_at: ahora, updated_at: ahora)	
		Responsable.update_all(created_at: ahora, updated_at: ahora)	
		Rol.update_all(created_at: ahora, updated_at: ahora)	
		TamanoContribuyente.update_all(created_at: ahora, updated_at: ahora)	
		Tarea.update_all(created_at: ahora, updated_at: ahora)	
		TipoAporte.update_all(created_at: ahora, updated_at: ahora)	
		TipoComentario.update_all(created_at: ahora, updated_at: ahora)	
		TipoContribuyente.update_all(created_at: ahora, updated_at: ahora)	
		TipoDeMedio.update_all(created_at: ahora, updated_at: ahora)	
		TipoDocumentoDiagnostico.update_all(created_at: ahora, updated_at: ahora)	
		TipoDocumentoGarantia.update_all(created_at: ahora, updated_at: ahora)	
		TipoInstrumento.update_all(created_at: ahora, updated_at: ahora)	
		TipoProveedor.update_all(created_at: ahora, updated_at: ahora)	
		Variable.update_all(created_at: ahora, updated_at: ahora)	

	  # devuelve la condición not null
	  change_column_null :accion_clasificaciones, :created_at, false
	  change_column_null :accion_clasificaciones, :updated_at, false
	  change_column_null :accion_relacionadas, :created_at, false
	  change_column_null :accion_relacionadas, :updated_at, false
	  change_column_null :acciones, :created_at, false
	  change_column_null :acciones, :updated_at, false	  
	  change_column_null :actividad_economicas, :created_at, false
	  change_column_null :actividad_economicas, :updated_at, false
	  change_column_null :actividad_items, :created_at, false
	  change_column_null :actividad_items, :updated_at, false
	  change_column_null :actividad_por_lineas, :created_at, false
	  change_column_null :actividad_por_lineas, :updated_at, false
	  change_column_null :actividades, :created_at, false
	  change_column_null :actividades, :updated_at, false
	  change_column_null :alcances, :created_at, false
	  change_column_null :alcances, :updated_at, false
	  change_column_null :cargos, :created_at, false
	  change_column_null :cargos, :updated_at, false
	  change_column_null :centro_de_costos, :created_at, false
	  change_column_null :centro_de_costos, :updated_at, false	  
	  change_column_null :clasificaciones, :created_at, false
	  change_column_null :clasificaciones, :updated_at, false	
	  change_column_null :contribuyentes, :created_at, false
	  change_column_null :contribuyentes, :updated_at, false
	  change_column_null :dato_anual_contribuyentes, :created_at, false
	  change_column_null :dato_anual_contribuyentes, :updated_at, false
	  change_column_null :descargable_tareas, :created_at, false
	  change_column_null :descargable_tareas, :updated_at, false
	  change_column_null :documento_diagnosticos, :created_at, false
	  change_column_null :documento_diagnosticos, :updated_at, false
	  change_column_null :ejecucion_presupuestarias, :created_at, false
	  change_column_null :ejecucion_presupuestarias, :updated_at, false
	  change_column_null :estado_admisibilidades, :created_at, false
	  change_column_null :estado_admisibilidades, :updated_at, false
	  change_column_null :estado_documento_garantias, :created_at, false
	  change_column_null :estado_documento_garantias, :updated_at, false
	  change_column_null :estado_rendiciones, :created_at, false
	  change_column_null :estado_rendiciones, :updated_at, false
	  change_column_null :estado_tarea_pendientes, :created_at, false
	  change_column_null :estado_tarea_pendientes, :updated_at, false
	  change_column_null :etapas, :created_at, false
	  change_column_null :etapas, :updated_at, false
	  change_column_null :feriados, :created_at, false
	  change_column_null :feriados, :updated_at, false
	  change_column_null :flujo_tareas, :created_at, false
	  change_column_null :flujo_tareas, :updated_at, false
	  change_column_null :glosas, :created_at, false
	  change_column_null :glosas, :updated_at, false
	  change_column_null :hito_de_prensa_instrumentos, :created_at, false
	  change_column_null :hito_de_prensa_instrumentos, :updated_at, false
	  change_column_null :hito_de_prensa_responsables, :created_at, false
	  change_column_null :hito_de_prensa_responsables, :updated_at, false
	  change_column_null :instrumentos, :created_at, false
	  change_column_null :instrumentos, :updated_at, false
	  change_column_null :lugar_coordenadas, :created_at, false
	  change_column_null :lugar_coordenadas, :updated_at, false
	  change_column_null :materia_sustancia_clasificaciones, :created_at, false
	  change_column_null :materia_sustancia_clasificaciones, :updated_at, false
	  change_column_null :materia_sustancias, :created_at, false
	  change_column_null :materia_sustancias, :updated_at, false
	  change_column_null :modalidades, :created_at, false
	  change_column_null :modalidades, :updated_at, false
	  change_column_null :persona_cargos, :created_at, false
	  change_column_null :persona_cargos, :updated_at, false
	  change_column_null :proveedor_tipo_proveedores, :created_at, false
	  change_column_null :proveedor_tipo_proveedores, :updated_at, false
	  change_column_null :provincias, :created_at, false
	  change_column_null :provincias, :updated_at, false
	  change_column_null :proyecto_actividades, :created_at, false
	  change_column_null :proyecto_actividades, :updated_at, false
	  change_column_null :proyecto_pagos, :created_at, false
	  change_column_null :proyecto_pagos, :updated_at, false
	  change_column_null :rango_venta_contribuyentes, :created_at, false
	  change_column_null :rango_venta_contribuyentes, :updated_at, false
	  change_column_null :regiones, :created_at, false
	  change_column_null :regiones, :updated_at, false
	  change_column_null :responsables, :created_at, false
	  change_column_null :responsables, :updated_at, false
	  change_column_null :roles, :created_at, false
	  change_column_null :roles, :updated_at, false
	  change_column_null :tamano_contribuyentes, :created_at, false
	  change_column_null :tamano_contribuyentes, :updated_at, false
	  change_column_null :tareas, :created_at, false
	  change_column_null :tareas, :updated_at, false
	  change_column_null :tipo_aportes, :created_at, false
	  change_column_null :tipo_aportes, :updated_at, false
	  change_column_null :tipo_comentarios, :created_at, false
	  change_column_null :tipo_comentarios, :updated_at, false
	  change_column_null :tipo_contribuyentes, :created_at, false
	  change_column_null :tipo_contribuyentes, :updated_at, false
	  change_column_null :tipo_de_medios, :created_at, false
	  change_column_null :tipo_de_medios, :updated_at, false
	  change_column_null :tipo_documento_diagnosticos, :created_at, false
	  change_column_null :tipo_documento_diagnosticos, :updated_at, false
	  change_column_null :tipo_documento_garantias, :created_at, false
	  change_column_null :tipo_documento_garantias, :updated_at, false
	  change_column_null :tipo_instrumentos, :created_at, false
	  change_column_null :tipo_instrumentos, :updated_at, false
	  change_column_null :tipo_proveedores, :created_at, false
	  change_column_null :tipo_proveedores, :updated_at, false
	  change_column_null :variables, :created_at, false
	  change_column_null :variables, :updated_at, false
  end
end
