class EstadoTareaPendiente < ApplicationRecord
	NO_INICIADA						= 1 #DZC NO_INICIADA SE UTILIZA CUANDO LA TAREA ESTA PENDIENTE Y DISPONIBLE PARA EL USUARIO
	ENVIADA								= 2 #DZC ENVIADA SE UTILIZA CUANDO LA TAREA ESTA TERMINADA

	#DZC no se esta usando
	# DEVUELTA_CON_ERRORES	= 3
	# REENVIADA							= 4
	# ACEPTADA							= 5
	# INICIADA							= 6
end