concurrency: 10
verbose: true
attentive:
  # Time in seconds between checks for disappeared jobs
  execution_interval: 1800  # default: 600
  # Time limit in seconds to perform disappeared jobs check
  timeout_interval: 60     # default: 60
queues:
  - default
  - [mailers, 2]
limits:
  default: 15
  mailers: 5  # Limitar a 5 emails por minuto
